/**
 * What the site reads out of the repository at build time: the "First app" sample from the entry
 * skill, and the sixteen recipes that become `/docs/guides/<name>/`.
 *
 * Nothing here is transcribed by hand. The home page's code block is the same text the docs harness
 * compiles (`AGENTS.md`: "Skill examples are compiled by the harness"), and a guide page is the
 * recipe page, unchanged, with its links rewritten.
 */
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { blobUrl } from "../site.config.ts";

/** Where the recipes live, relative to the repository root. */
export const RECIPES_DIRECTORY = "skills/ignifx/references/recipes";

/**
 * The guide groups of `03-pages-and-copy.md` §5, by recipe name.
 *
 * The set is asserted against `skills/ignifx/references/recipes/` at build time, so a recipe added
 * to the repository without a group here fails the build rather than disappearing from the site.
 */
export const GUIDE_GROUPS: readonly { readonly title: string; readonly recipes: readonly string[] }[] = [
  { title: "Scenes and assets", recipes: ["load-a-model", "spawn-a-prefab", "spawn-a-prefab-on-click"] },
  { title: "Rendering and motion", recipes: ["tween-a-transform"] },
  { title: "Input", recipes: ["bind-an-action-and-read-it", "rebind-a-key-at-runtime"] },
  { title: "3D", recipes: ["character-controller-3d", "third-person-camera", "raycast-and-trigger-3d"] },
  {
    title: "2D",
    recipes: ["animate-a-sprite-from-an-atlas", "load-a-tilemap-with-collision", "platformer-controller-2d"],
  },
  { title: "Audio", recipes: ["play-a-one-shot-and-a-loop"] },
  { title: "UI", recipes: ["build-a-pause-menu"] },
  { title: "Saving", recipes: ["save-and-load-game-state"] },
  { title: "Tools", recipes: ["show-diagnostics-in-devtools"] },
];

/** One recipe, as the guides index and the guide page read it. */
export interface Guide {
  /** The file name without `.md`; also the last segment of the route. */
  readonly name: string;
  /** `/docs/guides/<name>/`. */
  readonly route: string;
  /** The `#` heading. */
  readonly title: string;
  /** The first sentence of the first paragraph, for the index. */
  readonly line: string;
  /** The full Markdown source. */
  readonly source: string;
  /** The `blob/main` URL of the recipe page. */
  readonly url: string;
  /** The group heading it sits under. */
  readonly group: string;
}

const HEADING = /^#\s+(?<title>.+?)\s*$/u;
const SENTENCE_END = /\.(?:\s|$)/u;
const MARKDOWN_LINK = /\[([^\]]*)\]\([^)\s]*(?:\s+"[^"]*")?\)/gu;
const INLINE_CODE = /`([^`]+)`/gu;

/**
 * Reads a Markdown file's `#` title.
 *
 * @param source - The file's text.
 * @param fallback - Used when the file has no `#` heading.
 * @returns The title.
 */
function titleOf(source: string, fallback: string): string {
  for (const line of source.split("\n")) {
    const match = HEADING.exec(line);
    if (match !== null) {
      return match.groups?.["title"] ?? fallback;
    }
  }
  return fallback;
}

/**
 * Reads a Markdown file's first prose sentence, with links and code fences flattened to text.
 *
 * @param source - The file's text.
 * @returns One sentence, or an empty string when the file opens with a heading and a fence.
 */
function firstSentenceOf(source: string): string {
  const collected: string[] = [];
  let seenTitle = false;
  let inFence = false;
  for (const raw of source.split("\n")) {
    const line = raw.trim();
    if (line.startsWith("```")) {
      inFence = !inFence;
      continue;
    }
    if (inFence) {
      continue;
    }
    if (!seenTitle) {
      seenTitle = HEADING.test(line);
      continue;
    }
    if (line === "") {
      if (collected.length > 0) {
        break;
      }
      continue;
    }
    // A generated page opens with a `<!-- Generated by … -->` comment between the title and the
    // prose; it is not the sentence the index wants.
    if (line.startsWith("<!--")) {
      continue;
    }
    if (line.startsWith("#") || line.startsWith("|") || line.startsWith("-") || line.startsWith(">")) {
      break;
    }
    collected.push(line);
  }
  const paragraph = collected.join(" ").replaceAll(MARKDOWN_LINK, "$1").replaceAll(INLINE_CODE, "$1");
  const end = SENTENCE_END.exec(paragraph);
  return end === null ? paragraph : paragraph.slice(0, end.index + 1);
}

/**
 * Reads every guide, in the order {@link GUIDE_GROUPS} lists them.
 *
 * @param repositoryRoot - Absolute path to the repository root.
 * @returns The guides.
 * @throws When a grouped recipe has no file, or a recipe file has no group.
 */
export function readGuides(repositoryRoot: string): readonly Guide[] {
  const directory = path.join(repositoryRoot, RECIPES_DIRECTORY);
  const guides: Guide[] = [];
  for (const group of GUIDE_GROUPS) {
    for (const name of group.recipes) {
      const file = path.join(directory, `${name}.md`);
      if (!existsSync(file)) {
        throw new Error(
          `website: ${RECIPES_DIRECTORY}/${name}.md is listed in GUIDE_GROUPS but does not exist. Update scripts/repo-content.ts.`,
        );
      }
      const source = readFileSync(file, "utf8");
      guides.push({
        name,
        route: `/docs/guides/${name}/`,
        title: titleOf(source, name),
        line: firstSentenceOf(source),
        source,
        url: blobUrl(`${RECIPES_DIRECTORY}/${name}.md`),
        group: group.title,
      });
    }
  }
  return guides;
}

/**
 * Checks that every recipe in the repository is in a guide group.
 *
 * The recipes index (`skills/ignifx/references/recipes/README.md`) is the list `pnpm docs:recipes`
 * maintains; this compares it with {@link GUIDE_GROUPS} so a new recipe cannot be published to the
 * skill and silently miss the site.
 *
 * @param repositoryRoot - Absolute path to the repository root.
 * @returns Recipe names that have no group, sorted.
 */
export function ungroupedRecipes(repositoryRoot: string): readonly string[] {
  const readme = path.join(repositoryRoot, RECIPES_DIRECTORY, "README.md");
  if (!existsSync(readme)) {
    return [];
  }
  const grouped = new Set(GUIDE_GROUPS.flatMap((group) => group.recipes));
  const listed = new Set<string>();
  for (const match of readFileSync(readme, "utf8").matchAll(/^\|\s*\[`(?<name>[a-z\d-]+)`\]/gmu)) {
    const name = match.groups?.["name"];
    if (name !== undefined) {
      listed.add(name);
    }
  }
  return [...listed].filter((name) => !grouped.has(name)).toSorted((left, right) => left.localeCompare(right));
}

/**
 * Rewrites one link found inside a recipe page.
 *
 * A sibling recipe becomes its guide route, the recipes index becomes the guides index, and
 * everything else that lives in the repository becomes a `blob/main` URL — the site serves no skill
 * pages any more (`01-strategy-and-ia.md` §10).
 *
 * @param href - The raw target from the Markdown.
 * @returns The URL to emit.
 */
export function resolveGuideLink(href: string): string {
  if (href === "" || href.startsWith("#") || href.startsWith("http") || href.startsWith("mailto:")) {
    return href;
  }
  const [target = "", hash] = href.split("#", 2);
  const suffix = hash === undefined ? "" : `#${hash}`;
  const resolved = path.posix.normalize(path.posix.join(RECIPES_DIRECTORY, target));
  if (resolved === `${RECIPES_DIRECTORY}/README.md`) {
    return `/docs/guides/${suffix}`;
  }
  const sibling = /^skills\/ignifx\/references\/recipes\/(?<name>[a-z\d-]+)\.md$/u.exec(resolved)?.groups?.["name"];
  if (sibling !== undefined) {
    return `/docs/guides/${sibling}/${suffix}`;
  }
  return `${blobUrl(resolved)}${suffix}`;
}

/**
 * Slices the `## First app` code block out of the entry skill.
 *
 * @param repositoryRoot - Absolute path to the repository root.
 * @returns The TypeScript source, without its fences.
 * @throws When the section or its fence is gone.
 */
export function readFirstAppSample(repositoryRoot: string): string {
  const file = path.join(repositoryRoot, "skills", "ignifx", "SKILL.md");
  const source = readFileSync(file, "utf8");
  const section = source.split(/^## /mu).find((block) => block.startsWith("First app"));
  if (section === undefined) {
    throw new Error(`website: skills/ignifx/SKILL.md has no "## First app" section to quote on the home page.`);
  }
  const fence = /^```ts\n(?<code>[\s\S]*?)\n```$/mu.exec(section)?.groups?.["code"];
  if (fence === undefined || fence.trim() === "") {
    throw new Error(`website: the "## First app" section of skills/ignifx/SKILL.md has no \`ts\` code fence.`);
  }
  return fence;
}
