/**
 * The `skill-lint` check of the documentation harness
 * (`docs/architecture/16-docs-harness-and-skill.md` §4). One function per rule:
 * `checkSkillHeader` (size, frontmatter), `checkSectionOrder` and `checkDeprecatedSection` (§2's
 * template, in `skill-template.ts`), `checkLinks`, `checkNesting`, `checkDeprecations`,
 * `checkMigrationPointer`, `checkTimePhrases` (§5's stale wording) and `checkImportPaths` (§5's
 * exact import paths). Each appends to one `problems` list, so a run reports every problem at once.
 */
import path from "node:path";
import { failed, passed, summarize } from "./check-result.ts";
import { parseFrontmatter } from "./frontmatter.ts";
import { exists, readText } from "./fs-tree.ts";
import { extractRelativeLinks, extractSections, sectionAt, stripFencedBlocks } from "./markdown.ts";
import { collectSkillExamples } from "./skill-examples.ts";
import { displayPath, listSkillMarkdown } from "./skill-files.ts";
import { checkDeprecatedSection, checkSectionOrder } from "./skill-template.ts";
import type { CheckResult, HarnessContext } from "./check-result.ts";
import type { SkillRoot } from "./skill-files.ts";

/** Hard cap on `SKILL.md` length (§4). */
const MAX_SKILL_LINES = 500;

/** Hard cap on the frontmatter `description` (Agent Skills spec, §1). */
const MAX_DESCRIPTION_LENGTH = 1024;

/** Directory whose Markdown is generated by TypeDoc and therefore exempt from prose rules. */
const GENERATED_SEGMENT = `${path.sep}references${path.sep}api${path.sep}`;

const SKILL_NAME = /^[a-z0-9]+(?:-[a-z0-9]+)*$/u;
const LEADING_PRONOUN = /^(?:i|we|you|your|my|our)\b/iu;

/**
 * Lists the values `metadata.ignifx-version` may take.
 *
 * @param releaseVersion - Version of `@ignifx/core`.
 * @returns The accepted values.
 */
function acceptedVersions(releaseVersion: string): readonly string[] {
  return releaseVersion === "0.0.0" ? [releaseVersion, "0.0.0-unreleased"] : [releaseVersion];
}

/**
 * Validates one skill's frontmatter and size.
 *
 * @param root - The skill being checked.
 * @param releaseVersion - Version of `@ignifx/core`.
 * @param problems - Collector the function appends messages to.
 */
function checkSkillHeader(root: SkillRoot, releaseVersion: string, problems: string[]): void {
  const source = readText(root.skillFile);
  const lineCount = source.split("\n").length;
  if (lineCount > MAX_SKILL_LINES) {
    problems.push(`${root.label}: ${String(lineCount)} lines, limit is ${String(MAX_SKILL_LINES)}`);
  }
  const { frontmatter, errors } = parseFrontmatter(source);
  for (const error of errors) {
    problems.push(`${root.label}: ${error}`);
  }
  if (frontmatter === null) {
    return;
  }
  const name = frontmatter.fields.get("name") ?? "";
  if (!SKILL_NAME.test(name)) {
    problems.push(`${root.label}: frontmatter \`name\` "${name}" is not lowercase-with-hyphens`);
  } else if (name !== root.name) {
    problems.push(`${root.label}: frontmatter \`name\` "${name}" does not match the directory "${root.name}"`);
  }
  const description = frontmatter.fields.get("description") ?? "";
  if (description === "") {
    problems.push(`${root.label}: frontmatter \`description\` is missing`);
  } else if (description.length > MAX_DESCRIPTION_LENGTH) {
    problems.push(`${root.label}: \`description\` is ${String(description.length)} chars, limit is 1024`);
  } else if (LEADING_PRONOUN.test(description)) {
    problems.push(`${root.label}: \`description\` must be third person (it starts with a first/second-person pronoun)`);
  }
  if ((frontmatter.fields.get("license") ?? "") === "") {
    problems.push(`${root.label}: frontmatter \`license\` is missing`);
  }
  const version = frontmatter.maps.get("metadata")?.get("ignifx-version") ?? "";
  if (version === "") {
    problems.push(`${root.label}: frontmatter \`metadata.ignifx-version\` is missing`);
  } else if (!acceptedVersions(releaseVersion).includes(version)) {
    problems.push(
      `${root.label}: \`metadata.ignifx-version\` is "${version}", expected one of ${acceptedVersions(releaseVersion)
        .map((value) => `"${value}"`)
        .join(", ")}`,
    );
  }
}

/**
 * Checks that every relative link in a Markdown file resolves to a file on disk.
 *
 * @param file - Absolute path to the Markdown file.
 * @param label - Path to show in messages.
 * @param source - File contents.
 * @param problems - Collector the function appends messages to.
 */
function checkLinks(file: string, label: string, source: string, problems: string[]): void {
  for (const link of extractRelativeLinks(source)) {
    const target = path.resolve(path.dirname(file), link.target);
    if (!exists(target)) {
      problems.push(`${label}:${String(link.line)}: broken relative link \`${link.target}\``);
    }
  }
}

/**
 * Checks that `references/` is nested at most one directory deep.
 *
 * @param root - The skill being checked.
 * @param file - Absolute path to a Markdown file inside the skill.
 * @param label - Path to show in messages.
 * @param problems - Collector the function appends messages to.
 */
function checkNesting(root: SkillRoot, file: string, label: string, problems: string[]): void {
  const relative = path.relative(path.join(root.directory, "references"), file);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    return;
  }
  if (relative.split(path.sep).length > 2) {
    problems.push(`${label}: references/ may nest one level (\`references/<dir>/<file>.md\`), no deeper`);
  }
}

/**
 * Checks that `@deprecated` is only mentioned inside a "Deprecated" section.
 *
 * @param label - Path to show in messages.
 * @param source - File contents.
 * @param problems - Collector the function appends messages to.
 */
function checkDeprecations(label: string, source: string, problems: string[]): void {
  const sections = extractSections(source);
  for (const [index, line] of source.split("\n").entries()) {
    if (!line.includes("@deprecated")) {
      continue;
    }
    const section = sectionAt(sections, index + 1);
    if (section === null || !section.title.toLowerCase().startsWith("deprecated")) {
      problems.push(`${label}:${String(index + 1)}: \`@deprecated\` is mentioned outside a "## Deprecated" section`);
    }
  }
}

/**
 * Checks the one-pointer rule for `docs/migrations/` (`CONSTITUTION.md` §5.3).
 *
 * @param root - The skill being checked.
 * @param file - Absolute path to a Markdown file inside the skill.
 * @param label - Path to show in messages.
 * @param source - File contents.
 * @param problems - Collector the function appends messages to.
 */
function checkMigrationPointer(root: SkillRoot, file: string, label: string, source: string, problems: string[]): void {
  const sections = extractSections(stripFencedBlocks(source));
  const hits = stripFencedBlocks(source)
    .split("\n")
    .map((line, index) => ({ line, number: index + 1 }))
    .filter((entry) => entry.line.includes("docs/migrations"));
  if (hits.length === 0) {
    return;
  }
  const isEntryFile = file === root.skillFile;
  for (const hit of hits) {
    const section = sectionAt(sections, hit.number);
    const allowed = isEntryFile && section !== null && section.title.toLowerCase().startsWith("where to look next");
    if (!allowed) {
      problems.push(
        `${label}:${String(hit.number)}: \`docs/migrations/\` may only be named by the pointer line in "## Where to look next"`,
      );
    }
  }
  if (isEntryFile && hits.length > 1) {
    problems.push(
      `${label}: \`docs/migrations/\` is named ${String(hits.length)} times; exactly one pointer line is allowed`,
    );
  }
}

/**
 * Phrasings that go stale the moment a release ships (§5: versions are stated explicitly).
 * A line may keep one by carrying {@link TIME_PHRASE_ALLOW}, which is how prose about runtime
 * behaviour ("the most recently enabled listener wins") stays legal.
 */
const TIME_PHRASES = ["recently", "new in", "now supports", "currently"] as const;

/** Comment that waives {@link TIME_PHRASES} for the line it appears on. */
const TIME_PHRASE_ALLOW = "<!-- lint-allow: time-phrase -->";

/** Import specifiers an example may use (§5: exact import paths, never pseudo-code). */
const ALLOWED_IMPORT_PREFIXES = ["@ignifx/", "node:", "virtual:ignifx/", "vite/"] as const;

/** Import specifiers an example may use verbatim. */
const ALLOWED_IMPORTS = new Set(["ignifx", "vite"]);

const IMPORT_LINE = /(?:from|import)\s+["'](?<specifier>[^"']+)["']/u;

/**
 * Checks that no skill page uses phrasing that dates itself.
 *
 * @param label - Path to show in messages.
 * @param source - File contents.
 * @param problems - Collector the function appends messages to.
 */
function checkTimePhrases(label: string, source: string, problems: string[]): void {
  for (const [index, line] of stripFencedBlocks(source).split("\n").entries()) {
    if (line.includes(TIME_PHRASE_ALLOW)) {
      continue;
    }
    const lower = line.toLowerCase();
    for (const phrase of TIME_PHRASES) {
      if (!new RegExp(`\\b${phrase}\\b`, "u").test(lower)) {
        continue;
      }
      problems.push(
        `${label}:${String(index + 1)}: time-sensitive phrasing "${phrase}" (§5: state the version instead);` +
          ` put ${TIME_PHRASE_ALLOW} on the line when the wording describes runtime behaviour`,
      );
    }
  }
}

/**
 * Checks that every example imports a specifier a reader can type verbatim.
 *
 * Relative paths and unknown bare packages are the two ways an example stops being copy-pasteable:
 * `./player.ts` only exists in the document's imagination, and a third-party package is a
 * dependency the reader has not been told to install. A block that shows one on purpose — the
 * Electron main-process entry point, say — opts out with `ts ignore-check`.
 *
 * @param context - The tree being inspected.
 * @param roots - The skills found in that tree.
 * @param problems - Collector the function appends messages to.
 */
function checkImportPaths(context: HarnessContext, roots: readonly SkillRoot[], problems: string[]): void {
  for (const example of collectSkillExamples(context, roots).examples) {
    for (const [index, line] of example.code.split("\n").entries()) {
      const specifier = IMPORT_LINE.exec(line)?.groups?.["specifier"];
      if (specifier === undefined) {
        continue;
      }
      if (ALLOWED_IMPORTS.has(specifier) || ALLOWED_IMPORT_PREFIXES.some((prefix) => specifier.startsWith(prefix))) {
        continue;
      }
      problems.push(
        `${example.label}:${String(example.line + index + 1)}: example imports "${specifier}";` +
          " §5 allows ignifx, @ignifx/*, vite, virtual:ignifx/* and node:* — tag the block `ts ignore-check` otherwise",
      );
    }
  }
}

/**
 * Runs the `skill-lint` check.
 *
 * @param context - The tree being inspected.
 * @param roots - The skills found in that tree.
 * @returns The check result.
 */
export function checkSkillLint(context: HarnessContext, roots: readonly SkillRoot[]): CheckResult {
  const problems: string[] = [];
  const files = listSkillMarkdown(roots);
  for (const root of roots) {
    const source = readText(root.skillFile);
    checkSkillHeader(root, context.releaseVersion, problems);
    checkSectionOrder(root, source, problems);
    checkDeprecatedSection(root, source, context.releaseVersion, problems);
  }
  checkImportPaths(context, roots, problems);
  for (const file of files) {
    const root = roots.find((candidate) => file.startsWith(`${candidate.directory}${path.sep}`));
    if (root === undefined) {
      continue;
    }
    const label = displayPath(context.repositoryRoot, file, context.skillsDirectory);
    const source = readText(file);
    checkLinks(file, label, source, problems);
    checkNesting(root, file, label, problems);
    if (!file.includes(GENERATED_SEGMENT)) {
      checkDeprecations(label, source, problems);
      checkMigrationPointer(root, file, label, source, problems);
      checkTimePhrases(label, source, problems);
    }
  }
  const versions = acceptedVersions(context.releaseVersion)
    .map((value) => `"${value}"`)
    .join(" or ");
  const notes = [`rule: metadata.ignifx-version must be ${versions} (@ignifx/core is ${context.releaseVersion})`];
  if (problems.length > 0) {
    return failed("skill-lint", `${String(problems.length)} problems`, [...summarize(problems, 20), ...notes]);
  }
  return passed("skill-lint", `${String(files.length)} files, ${String(roots.length)} skills`, notes);
}
