/**
 * Builds `website/public/llms.txt`, the index an agent browsing ignifx.com reads instead of
 * crawling the site (`docs/architecture/16-docs-harness-and-skill.md` §1). The file follows the
 * `llms.txt` convention: an `H1` name, a blockquote summary, then `## ` sections of
 * `- [title](url): one line` entries.
 *
 * Everything in it is derived from the tree, so it cannot drift: titles come from each page's `#`
 * heading and the one-liners from each page's first paragraph. Nothing here states project status,
 * which phase shipped, or anything else a person would have to remember to update.
 *
 * ## URL mapping
 *
 * The site (Phase 12) serves `skills/ignifx/**` under `/skill/`:
 *
 * | Repository path                              | URL                                  |
 * | -------------------------------------------- | ------------------------------------ |
 * | `skills/ignifx/SKILL.md`                     | `/skill/`                            |
 * | `skills/ignifx/references/<dir>/<name>.md`   | `/skill/references/<dir>/<name>`     |
 * | `skills/ignifx/references/gotchas.md`        | `/skill/references/gotchas`          |
 * | `packages/<pkg>/skills/<name>/SKILL.md`      | `/skill/<name>/`                     |
 *
 * `README.md` pages are left out: they index a directory for someone reading the repository, and
 * this file is that index for the site.
 */
import path from "node:path";
import { parseFrontmatter } from "./frontmatter.ts";
import { exists, listFilesRecursive, readText } from "./fs-tree.ts";
import { findSkillRoots } from "./skill-files.ts";
import type { SkillRoot } from "./skill-files.ts";

/** Longest one-liner kept before it is trimmed at a word boundary. */
const MAX_SUMMARY_LENGTH = 300;

/** Name of the entry skill directory under `skills/`. */
const ENTRY_SKILL = "ignifx";

/** Site path every skill file is served under. */
const SITE_ROOT = "/skill";

const HEADING = /^#\s+(?<title>.+?)\s*$/u;
const GENERATED_COMMENT = /^<!--\s*Generated by\s+(?<generator>`[^`]+`)\.?.*-->/u;
const SENTENCE_END = /\.(?:\s|$)/u;
const MARKDOWN_LINK = /\[([^\]]*)\]\([^)\s]*(?:\s+"[^"]*")?\)/gu;
const LIST_OR_BLOCK = /^(?:[-+*]\s|\d+\.\s|[#|>])/u;

/** One line of the index. */
interface IndexEntry {
  /** Link text. */
  readonly title: string;
  /** Site-root-relative URL. */
  readonly url: string;
  /** The one-line description after the colon. */
  readonly summary: string;
}

/**
 * Reads a Markdown file's `#` title.
 *
 * @param source - Full Markdown file contents.
 * @param fallback - Title to use when the file has no `#` heading.
 * @returns The title.
 */
function titleOf(source: string, fallback: string): string {
  for (const line of source.split("\n")) {
    const match = HEADING.exec(line);
    if (match !== null) {
      return match.groups?.["title"] ?? fallback;
    }
  }
  return fallback;
}

/**
 * Shortens a paragraph to its first sentence, then to {@link MAX_SUMMARY_LENGTH}.
 *
 * @param text - The paragraph, already collapsed onto one line.
 * @returns One sentence, or a word-boundary trim of it when it is very long.
 */
function firstSentence(text: string): string {
  const match = SENTENCE_END.exec(text);
  const sentence = match === null ? text : text.slice(0, match.index + 1);
  if (sentence.length <= MAX_SUMMARY_LENGTH) {
    return sentence;
  }
  const cut = sentence.lastIndexOf(" ", MAX_SUMMARY_LENGTH);
  return `${sentence.slice(0, cut === -1 ? MAX_SUMMARY_LENGTH : cut)}…`;
}

/**
 * Reads the one-liner for a page: the first sentence of its first paragraph.
 *
 * HTML comments, tables, fenced blocks, list items and blockquotes are skipped on the way. A
 * `SKILL.md` keeps its lead paragraph under a `##` heading, so `skipHeadings` scans past headings
 * for those; a reference page stops at its first `##`, which is what makes a generated field table
 * (a heading followed straight by a table) fall through to its `Generated by` comment instead of
 * lifting the first table cell it finds.
 *
 * @param source - Full Markdown file contents.
 * @param fallback - Summary to use when the page has neither a paragraph nor a generator comment.
 * @param skipHeadings - Whether to keep scanning past `##` headings (true for a `SKILL.md`).
 * @returns The one-line description.
 */
function summaryOf(source: string, fallback: string, skipHeadings: boolean): string {
  const lines = source.split("\n");
  let generator: string | null = null;
  const paragraph: string[] = [];
  let insideFence = false;
  let seenTitle = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("```")) {
      insideFence = !insideFence;
      continue;
    }
    if (insideFence) {
      continue;
    }
    if (!seenTitle) {
      seenTitle = HEADING.test(line);
      continue;
    }
    const comment = GENERATED_COMMENT.exec(trimmed);
    if (comment !== null) {
      generator ??= comment.groups?.["generator"] ?? null;
      continue;
    }
    if (trimmed === "") {
      if (paragraph.length > 0) {
        break;
      }
      continue;
    }
    if (LIST_OR_BLOCK.test(trimmed)) {
      if (trimmed.startsWith("#") && !skipHeadings) {
        break;
      }
      continue;
    }
    paragraph.push(trimmed);
  }
  if (paragraph.length > 0) {
    return firstSentence(paragraph.join(" ").replaceAll(MARKDOWN_LINK, "$1"));
  }
  return generator === null ? fallback : `Generated by ${generator}.`;
}

/**
 * Builds the entry for one reference page.
 *
 * @param file - Absolute path to the Markdown file.
 * @param url - The site URL it is served at.
 * @returns The index entry.
 */
function pageEntry(file: string, url: string): IndexEntry {
  const source = readText(file);
  const fallback = path.basename(file, ".md");
  return { title: titleOf(source, fallback), url, summary: summaryOf(source, fallback, false) };
}

/**
 * Lists the pages of one `references/<dir>` directory, `README.md` excluded.
 *
 * @param entrySkillDirectory - Absolute path to `skills/ignifx`.
 * @param directory - Directory name under `references/`.
 * @returns The entries, sorted by file name.
 */
function referenceEntries(entrySkillDirectory: string, directory: string): readonly IndexEntry[] {
  const absolute = path.join(entrySkillDirectory, "references", directory);
  return listFilesRecursive(absolute, ".md")
    .filter((file) => path.basename(file) !== "README.md")
    .map((file) => pageEntry(file, `${SITE_ROOT}/references/${directory}/${path.basename(file, ".md")}`));
}

/**
 * Builds the entry for one subsystem skill.
 *
 * @param root - The subsystem skill.
 * @returns The index entry.
 */
function subsystemEntry(root: SkillRoot): IndexEntry {
  const source = readText(root.skillFile);
  return {
    title: titleOf(source, root.name),
    url: `${SITE_ROOT}/${root.name}/`,
    summary: summaryOf(source, root.name, true),
  };
}

/**
 * Renders one `##` section, or nothing when it has no entries.
 *
 * @param heading - Section heading.
 * @param entries - The lines it holds.
 * @returns The section text, ending in a blank line, or an empty string.
 */
function renderSection(heading: string, entries: readonly IndexEntry[]): string {
  if (entries.length === 0) {
    return "";
  }
  const lines = entries.map((entry) => `- [${entry.title}](${entry.url}): ${entry.summary}`);
  return `## ${heading}\n\n${lines.join("\n")}\n\n`;
}

/**
 * Builds the whole `llms.txt` for a repository tree.
 *
 * @param root - Absolute path to the repository root.
 * @returns The file contents, ending in a newline.
 * @throws When the tree has no entry skill to index.
 */
export function renderLlmsIndex(root: string): string {
  const skillsDirectory = path.join(root, "skills");
  const roots = findSkillRoots(root, skillsDirectory);
  const entryDirectory = path.join(skillsDirectory, ENTRY_SKILL);
  const entryRoot = roots.find((candidate) => candidate.directory === entryDirectory);
  if (entryRoot === undefined || !exists(entryRoot.skillFile)) {
    throw new Error(`no entry skill at ${path.join("skills", ENTRY_SKILL, "SKILL.md")}`);
  }
  const entrySource = readText(entryRoot.skillFile);
  const description = parseFrontmatter(entrySource).frontmatter?.fields.get("description") ?? "";
  const subsystems = roots
    .filter((candidate) => candidate !== entryRoot)
    .toSorted((left, right) => left.name.localeCompare(right.name));

  const documents: IndexEntry[] = [
    {
      title: titleOf(entrySource, ENTRY_SKILL),
      url: `${SITE_ROOT}/`,
      summary: summaryOf(entrySource, ENTRY_SKILL, true),
    },
  ];
  const gotchas = path.join(entryDirectory, "references", "gotchas.md");
  if (exists(gotchas)) {
    documents.push(pageEntry(gotchas, `${SITE_ROOT}/references/gotchas`));
  }

  return (
    "<!-- Generated by `pnpm docs:llms` from skills/ and packages/*/skills/. Do not edit by hand. -->\n\n" +
    `# ${titleOf(entrySource, ENTRY_SKILL)}\n\n` +
    `> ${firstSentence(description)}\n\n` +
    `The pages below are the Agent Skill that ships with the engine, served under \`${SITE_ROOT}/\`.\n\n` +
    renderSection("Docs", documents) +
    renderSection("Concepts", referenceEntries(entryDirectory, "concepts")) +
    renderSection("Recipes", referenceEntries(entryDirectory, "recipes")) +
    renderSection("File formats", referenceEntries(entryDirectory, "formats")) +
    renderSection("API reference", referenceEntries(entryDirectory, "api")) +
    renderSection(
      "Extensions",
      subsystems.map((subsystem) => subsystemEntry(subsystem)),
    )
  );
}
