/**
 * Extraction and rendering for `pnpm docs:recipes`. The convention the parser implements is
 * documented in `scripts/docs-recipes.ts` and `scripts/README.md`.
 */
import { readText } from "./fs-tree.ts";

/** Cap on the lines of code one recipe may contain (16-docs-harness-and-skill.md §5). */
export const RECIPE_MAX_CODE_LINES = 80;

/**
 * Directive a recipe puts on the first line after its doc comment to have the harness **execute**
 * the page's block, not only type-check it (`scripts/README.md`, "Executable examples").
 *
 * It is a line comment rather than a doc-comment tag because `jsdoc/check-tag-names` rejects any
 * tag outside the TSDoc set the repository declares in `eslint.config.ts`. The line is consumed by
 * the generator, so it never reaches the page and never counts against the 80-line cap.
 */
export const RECIPE_RUN_DIRECTIVE = "// docs:run";

/** A recipe extracted from `examples/recipes/<name>/main.ts`. */
export interface Recipe {
  /** Directory name, used for the output file name. */
  readonly name: string;
  /** Title taken from the first line of the leading doc comment. */
  readonly title: string;
  /** Remaining prose from the leading doc comment. */
  readonly prose: string;
  /** The recipe source, with the leading doc comment removed. */
  readonly code: string;
  /** Whether the block is tagged `ts run`, so `examples-run` executes it. */
  readonly run: boolean;
  /** Repository-relative path of the source file. */
  readonly source: string;
}

/** Outcome of extracting one recipe. */
export interface RecipeResult {
  /** The recipe, or `null` when extraction failed. */
  readonly recipe: Recipe | null;
  /** Reasons extraction failed. */
  readonly errors: readonly string[];
}

/**
 * Strips the ` * ` decoration from the body of a block comment.
 *
 * @param body - The comment body between the delimiters.
 * @returns The undecorated lines, joined by newlines and trimmed.
 */
function undecorate(body: string): string {
  return body
    .split("\n")
    .map((line) => line.replace(/^\s*\*\s?/u, ""))
    .join("\n")
    .trim();
}

/**
 * Extracts the leading doc comment and the code that follows it.
 *
 * @param name - Recipe directory name.
 * @param file - Absolute path to `main.ts`.
 * @returns The extracted recipe, or the reasons it could not be extracted.
 */
export function extractRecipe(name: string, file: string): RecipeResult {
  const source = readText(file);
  const start = source.indexOf("/**");
  const end = source.indexOf("*/", start + 3);
  if (start === -1 || end === -1 || source.slice(0, start).trim() !== "") {
    return { recipe: null, errors: ["main.ts must open with a `/** ... */` doc comment describing the recipe"] };
  }
  const documentation = undecorate(source.slice(start + 3, end));
  const [titleLine, ...bodyLines] = documentation.split("\n");
  const title = (titleLine ?? "").trim();
  if (title === "") {
    return { recipe: null, errors: ["the leading doc comment must start with a one-line title"] };
  }
  const body = source.slice(end + 2).trim();
  const run = body.startsWith(RECIPE_RUN_DIRECTIVE);
  const code = run ? body.slice(RECIPE_RUN_DIRECTIVE.length).trim() : body;
  if (code === "") {
    return { recipe: null, errors: ["there is no code after the leading doc comment"] };
  }
  const lineCount = code.split("\n").length;
  if (lineCount > RECIPE_MAX_CODE_LINES) {
    const detail = `${String(lineCount)} lines of code, limit is ${String(RECIPE_MAX_CODE_LINES)}`;
    return { recipe: null, errors: [`recipe is too long (${detail}); split it into two recipes`] };
  }
  return {
    recipe: { name, title, prose: bodyLines.join("\n").trim(), code, run, source: `examples/recipes/${name}/main.ts` },
    errors: [],
  };
}

/**
 * Renders one recipe page.
 *
 * @param recipe - The extracted recipe.
 * @returns The full Markdown page.
 */
export function renderRecipePage(recipe: Recipe): string {
  const lines = [`# ${recipe.title}`, "", "<!-- Generated by `pnpm docs:recipes`. Do not edit by hand. -->", ""];
  if (recipe.prose !== "") {
    lines.push(recipe.prose, "");
  }
  lines.push(recipe.run ? "```ts run" : "```ts", recipe.code, "```", "", `Source: \`${recipe.source}\``);
  return `${lines.join("\n")}\n`;
}
