/**
 * Rendering half of `pnpm docs:schemas`: turns normalized schemas into the Markdown tables and the
 * JSON bundle under `skills/ignifx/references/formats/`.
 */
import type { SchemaDoc } from "./schema-source.ts";

/** Notice stamped into every generated file so a human editing it is warned. */
export const GENERATED_NOTICE = "<!-- Generated by `pnpm docs:schemas`. Do not edit by hand. -->";

/**
 * Escapes the pipe characters that would otherwise break a Markdown table cell.
 *
 * @param text - Raw cell text.
 * @returns Text safe to place inside a table cell.
 */
function cell(text: string): string {
  return text.replaceAll("|", "\\|").replaceAll("\n", " ").trim();
}

/**
 * Renders one `references/formats/<format>.md` page.
 *
 * @param format - The format group name.
 * @param schemas - The schemas that belong to it, sorted by type id.
 * @returns The full Markdown page.
 */
export function renderFormatPage(format: string, schemas: readonly SchemaDoc[]): string {
  const lines: string[] = [`# ${format}`, "", GENERATED_NOTICE, ""];
  for (const schema of schemas) {
    lines.push(`## ${schema.title} (\`${schema.typeId}\`)`, "");
    if (schema.description !== "") {
      lines.push(schema.description, "");
    }
    lines.push("| Field | Kind | Default | Description |", "|---|---|---|---|");
    for (const field of schema.fields) {
      const defaultCell = field.defaultValue === null ? "—" : `\`${field.defaultValue}\``;
      lines.push(`| \`${cell(field.name)}\` | \`${cell(field.kind)}\` | ${defaultCell} | ${cell(field.description)} |`);
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

/**
 * Renders the `ignifx.schemas.json` bundle.
 *
 * @param version - The current release version of the fixed version line.
 * @param schemas - Every schema in the workspace, sorted by type id.
 * @returns Pretty-printed JSON with a trailing newline.
 */
export function renderSchemaBundle(version: string, schemas: readonly SchemaDoc[]): string {
  const bundle = {
    generatedBy: "pnpm docs:schemas",
    ignifxVersion: version,
    schemas: Object.fromEntries(
      schemas.map((schema) => [
        schema.typeId,
        {
          title: schema.title,
          format: schema.format,
          description: schema.description,
          package: `packages/${schema.packageDirectory}`,
          fields: Object.fromEntries(
            schema.fields.map((field) => [
              field.name,
              { kind: field.kind, default: field.defaultValue, description: field.description },
            ]),
          ),
        },
      ]),
    ),
  };
  return `${JSON.stringify(bundle, null, 2)}\n`;
}
