import { LOOKUP_SAMPLES } from "../definition/types.js";
import { PARTICLE_SALT_Y, PARTICLE_SALT_Z } from "../emitter/pcg3d.js";
import type { LookupRow, ParticleDefinition, ScalarValue } from "../definition/types.js";

// The GPU evaluator: one `.wgsl` program generated per definition
// (`docs/plan/2026-09-terrain-particles-shaders.md` §4.4), the second host of the specification
// `src/evaluate/particle-math.ts` states in TypeScript. Read the two side by side.

/** Degrees to radians, as a WGSL literal. */
const DEG_TO_RAD_WGSL = "0.017453292519943295";

/** The offsets the second and third noise channels sample at. */
const NOISE_OFFSET_Y = "vec3<f32>(31.4, 47.2, 12.9)";

/** The offsets the second and third noise channels sample at. */
const NOISE_OFFSET_Z = "vec3<f32>(-17.3, 8.6, 53.1)";

/**
 * Formats a number as a WGSL `f32` literal.
 *
 * @param value - The number.
 * @returns The literal, always with a decimal point or an exponent.
 */
function f32(value: number): string {
  if (!Number.isFinite(value)) {
    return "0.0";
  }
  const text = String(value);
  return text.includes(".") || text.includes("e") ? text : `${text}.0`;
}

/**
 * Formats three numbers as a `vec3<f32>` literal.
 *
 * @param x - The first component.
 * @param y - The second component.
 * @param z - The third component.
 * @returns The literal.
 */
function vec3(x: number, y: number, z: number): string {
  return `vec3<f32>(${f32(x)}, ${f32(y)}, ${f32(z)})`;
}

/**
 * The WGSL of the row constants a lookup row needs.
 *
 * @param name - The constant prefix.
 * @param row - The row.
 * @returns The declarations.
 */
function rowConstants(name: string, row: LookupRow): string {
  return `const ${name}_ROW: f32 = ${f32(row.index)};\nconst ${name}_MIN: f32 = ${f32(row.min)};\nconst ${name}_MAX: f32 = ${f32(row.max)};\n`;
}

/**
 * The WGSL that reads a decoded scalar row into a variable.
 *
 * @param name - The constant prefix used by {@link rowConstants}.
 * @param channel - The swizzle to read.
 * @returns An expression.
 */
function decodeRow(name: string, channel: string): string {
  return `(${name}_MIN + lookupRow(${name}_ROW, life).${channel} * (${name}_MAX - ${name}_MIN))`;
}

/**
 * The WGSL expression for a constant or random scalar picked by a unit float.
 *
 * @param value - The scalar; a curve is handled by the caller through its row.
 * @param unit - The unit float expression.
 * @returns An expression.
 */
function pickScalar(value: ScalarValue, unit: string): string {
  if (value.kind === "constant") {
    return f32(value.value);
  }
  if (value.kind === "random") {
    return `mix(${f32(value.min)}, ${f32(value.max)}, ${unit})`;
  }
  return "0.0";
}

/**
 * Generates the WGSL program that draws a definition.
 *
 * @param definition - The definition.
 * @returns The whole `.wgsl` source, pragmas included, ready for the shader loader.
 *
 * @example
 * ```ts
 * const source = generateParticleWgsl(particleDefinition("fire"));
 * source.includes("@ignifx blend premultiplied"); // true
 * ```
 *
 * @beta
 */
export function generateParticleWgsl(definition: ParticleDefinition): string {
  const { forces, renderer, start, lookup } = definition;
  const isMesh = renderer.mode === "mesh";
  const system: string[] = ["view", "viewProjection"];
  if (renderer.mode === "vertical") {
    system.push("cameraPosition");
  }
  if (renderer.lit) {
    system.push("mainLightDirection", "mainLightColor", "ambientColor");
  }
  const attributes = isMesh ? "position, normal, uv" : "position, uv";
  const parts: string[] = [];
  // Every binding and uniform below is declared only when the program reads it: Babylon Lite
  // demands that a declared sampler or storage buffer be bound before the material can draw.
  parts.push(
    "// Generated by @ignifx/particles from an ignifx.particles definition. Do not edit.",
    "// @ignifx shader",
    `// @ignifx attributes ${attributes}`,
    `// @ignifx system ${system.join(", ")}`,
    "// @ignifx storage particles: array<Particle>",
    ...(renderer.texture === null ? [] : ["// @ignifx texture sheet srgb default white"]),
    "// @ignifx texture lut default white",
    "// @ignifx uniform clock: f32 = 0",
    "// @ignifx uniform head: f32 = 0",
    "// @ignifx uniform capacity: f32 = 1",
    ...(definition.main.simulationSpace === "local" ? ["// @ignifx uniform emitterWorld: mat4x4<f32>"] : []),
    ...(forces.orbit === null ? [] : ["// @ignifx uniform orbitCenter: vec3<f32> = (0, 0, 0)"]),
    "// @ignifx uniform gravity: vec3<f32> = (0, 0, 0)",
    `// @ignifx blend ${renderer.blend} cull none depthWrite off instancing matrices`,
    "",
    "struct Particle {",
    "  spawnTime: f32,",
    "  lifetime: f32,",
    "  seed: u32,",
    "  flags: u32,",
    "  @align(16) position: vec3<f32>,",
    "  size: f32,",
    "  @align(16) velocity: vec3<f32>,",
    "  rotation: f32,",
    "}",
    "",
    "struct VertexOutput {",
    "  @builtin(position) position: vec4<f32>,",
    "  @location(0) uv: vec2<f32>,",
    "  @location(1) color: vec4<f32>,",
    "}",
    "",
    `const DEG_TO_RAD: f32 = ${DEG_TO_RAD_WGSL};`,
    `const LOOKUP_ROWS: f32 = ${f32(lookup.rows)};`,
    `const LOOKUP_LAST: f32 = ${f32(LOOKUP_SAMPLES - 1)};`,
    `const LOOKUP_WIDTH: f32 = ${f32(LOOKUP_SAMPLES)};`,
    `const SALT_Y: u32 = ${String(PARTICLE_SALT_Y)}u;`,
    `const SALT_Z: u32 = ${String(PARTICLE_SALT_Z)}u;`,
    "const UNIT_SCALE: f32 = 2.3283064365386963e-10;",
    "const DEAD: vec4<f32> = vec4<f32>(0.0, 0.0, 2.0, 1.0);",
    `const DRAG: f32 = ${f32(forces.drag)};`,
    `const SIZE_SCALE: vec3<f32> = ${vec3(start.size3D?.x ?? 1, start.size3D?.y ?? 1, start.size3D?.z ?? 1)};`,
    `const PIVOT: vec2<f32> = vec2<f32>(${f32(renderer.pivot.x)}, ${f32(renderer.pivot.y)});`,
    "",
  );
  const startColor = start.color;
  if (startColor.kind === "random") {
    parts.push(
      `const START_COLOR_MIN: vec4<f32> = vec4<f32>(${f32(startColor.min.r)}, ${f32(startColor.min.g)}, ${f32(startColor.min.b)}, ${f32(startColor.min.a)});`,
      `const START_COLOR_MAX: vec4<f32> = vec4<f32>(${f32(startColor.max.r)}, ${f32(startColor.max.g)}, ${f32(startColor.max.b)}, ${f32(startColor.max.a)});`,
    );
  } else {
    const c = startColor.kind === "constant" ? startColor.value : { r: 1, g: 1, b: 1, a: 1 };
    parts.push(`const START_COLOR: vec4<f32> = vec4<f32>(${f32(c.r)}, ${f32(c.g)}, ${f32(c.b)}, ${f32(c.a)});`);
  }
  if (lookup.color !== null) {
    parts.push(rowConstants("COLOR", lookup.color));
  }
  if (lookup.size !== null) {
    parts.push(rowConstants("SIZE", lookup.size));
  }
  if (lookup.rotation !== null) {
    parts.push(rowConstants("ROTATION", lookup.rotation));
  }
  if (lookup.noise !== null) {
    parts.push(rowConstants("NOISE", lookup.noise));
  }
  if (lookup.frame !== null) {
    parts.push(rowConstants("FRAME", lookup.frame));
  }
  const orbit = forces.orbit;
  if (orbit !== null) {
    parts.push(
      `const ORBIT_AXIS: vec3<f32> = ${vec3(orbit.axis.x, orbit.axis.y, orbit.axis.z)};`,
      `const ORBIT_SPEED: f32 = ${f32(orbit.speed)};`,
    );
  }
  const noise = forces.noise;
  if (noise !== null) {
    parts.push(
      `const NOISE_STRENGTH: f32 = ${f32(noise.strength)};`,
      `const NOISE_FREQUENCY: f32 = ${f32(noise.frequency)};`,
      `const NOISE_SCROLL: vec3<f32> = ${vec3(noise.scroll.x, noise.scroll.y, noise.scroll.z)};`,
      `const NOISE_OCTAVES: i32 = ${String(noise.octaves)};`,
      `const NOISE_INFLUENCE: f32 = ${f32(noise.influenceOverLife.kind === "constant" ? noise.influenceOverLife.value : 1)};`,
    );
  }
  const sheet = renderer.sheet;
  if (sheet !== null) {
    parts.push(
      `const SHEET_TILES: vec2<f32> = vec2<f32>(${f32(sheet.tiles.x)}, ${f32(sheet.tiles.y)});`,
      `const SHEET_COUNT: f32 = ${f32(sheet.tiles.x * sheet.tiles.y)};`,
      `const SHEET_FPS: f32 = ${f32(sheet.fps)};`,
    );
  }
  if (renderer.mode === "stretched") {
    parts.push(
      `const SPEED_SCALE: f32 = ${f32(renderer.speedScale)};`,
      `const LENGTH_SCALE: f32 = ${f32(renderer.lengthScale)};`,
    );
  }
  parts.push("", HELPERS);
  if (noise !== null) {
    parts.push(NOISE_HELPERS);
  }
  parts.push(vertexStage(definition), "", fragmentStage(definition));
  return `${parts.join("\n")}\n`;
}

/** The helpers every program carries: `pcg3d`, sRGB decode, Rodrigues rotation, the row sampler. */
const HELPERS = `fn pcg3d(v0: vec3<u32>) -> vec3<u32> {
  var v = v0 * 1664525u + 1013904223u;
  v.x += v.y * v.z;
  v.y += v.z * v.x;
  v.z += v.x * v.y;
  v ^= v >> vec3<u32>(16u);
  v.x += v.y * v.z;
  v.y += v.z * v.x;
  v.z += v.x * v.y;
  return v;
}

fn srgbToLinear(c: vec3<f32>) -> vec3<f32> {
  let low = c / 12.92;
  let high = pow((c + vec3<f32>(0.055)) / 1.055, vec3<f32>(2.4));
  return select(high, low, c <= vec3<f32>(0.04045));
}

fn rotateAbout(v: vec3<f32>, axis: vec3<f32>, angle: f32) -> vec3<f32> {
  let c = cos(angle);
  let s = sin(angle);
  return v * c + cross(axis, v) * s + axis * dot(axis, v) * (1.0 - c);
}

fn lookupRow(row: f32, life: f32) -> vec4<f32> {
  let u = (clamp(life, 0.0, 1.0) * LOOKUP_LAST + 0.5) / LOOKUP_WIDTH;
  let v = (row + 0.5) / LOOKUP_ROWS;
  return textureSampleLevel(lut, lutSampler, vec2<f32>(u, v), 0.0);
}
`;

/** The gradient noise, line for line the TypeScript in `src/evaluate/noise.ts`. */
const NOISE_HELPERS = `fn fade(t: vec3<f32>) -> vec3<f32> {
  return t * t * t * (t * (t * 6.0 - 15.0) + 10.0);
}

fn cornerDot(cell: vec3<i32>, d: vec3<f32>) -> f32 {
  let h = pcg3d(bitcast<vec3<u32>>(cell));
  let g = vec3<f32>(h) * UNIT_SCALE * 2.0 - vec3<f32>(1.0);
  return dot(g, d);
}

fn gradientNoise(p: vec3<f32>) -> f32 {
  let i = floor(p);
  let f = p - i;
  let u = fade(f);
  let cell = vec3<i32>(i);
  let c000 = cornerDot(cell, f);
  let c100 = cornerDot(cell + vec3<i32>(1, 0, 0), f - vec3<f32>(1.0, 0.0, 0.0));
  let c010 = cornerDot(cell + vec3<i32>(0, 1, 0), f - vec3<f32>(0.0, 1.0, 0.0));
  let c110 = cornerDot(cell + vec3<i32>(1, 1, 0), f - vec3<f32>(1.0, 1.0, 0.0));
  let c001 = cornerDot(cell + vec3<i32>(0, 0, 1), f - vec3<f32>(0.0, 0.0, 1.0));
  let c101 = cornerDot(cell + vec3<i32>(1, 0, 1), f - vec3<f32>(1.0, 0.0, 1.0));
  let c011 = cornerDot(cell + vec3<i32>(0, 1, 1), f - vec3<f32>(0.0, 1.0, 1.0));
  let c111 = cornerDot(cell + vec3<i32>(1, 1, 1), f - vec3<f32>(1.0, 1.0, 1.0));
  let x00 = mix(c000, c100, u.x);
  let x10 = mix(c010, c110, u.x);
  let x01 = mix(c001, c101, u.x);
  let x11 = mix(c011, c111, u.x);
  let y0 = mix(x00, x10, u.y);
  let y1 = mix(x01, x11, u.y);
  return mix(y0, y1, u.z);
}

fn noise3(p: vec3<f32>) -> vec3<f32> {
  var n = vec3<f32>(gradientNoise(p), gradientNoise(p + ${NOISE_OFFSET_Y}), gradientNoise(p + ${NOISE_OFFSET_Z}));
  if (NOISE_OCTAVES >= 2) {
    let p2 = p * 2.0;
    n += 0.5 * vec3<f32>(gradientNoise(p2), gradientNoise(p2 + ${NOISE_OFFSET_Y}), gradientNoise(p2 + ${NOISE_OFFSET_Z}));
  }
  return n;
}
`;

/**
 * The vertex stage: record lookup, the closed forms, and the orientation of the mode.
 *
 * @param definition - The definition.
 * @returns The `mainVertex` function.
 */
function vertexStage(definition: ParticleDefinition): string {
  const { forces, renderer, start, overLifetime, lookup, main } = definition;
  const lines: string[] = [];
  lines.push(
    "@vertex fn mainVertex(input: VertexInput, @builtin(instance_index) iid: u32) -> VertexOutput {",
    "  var out: VertexOutput;",
    "  let capacity = u32(shaderUniforms.capacity);",
    "  let head = u32(shaderUniforms.head);",
    "  let slot = (head + capacity - 1u - iid) % capacity;",
    "  let record = particles[slot];",
    "  let age = shaderUniforms.clock - record.spawnTime;",
    "  if (age < 0.0 || age > record.lifetime || record.lifetime <= 0.0) {",
    "    out.position = DEAD;",
    "    out.uv = vec2<f32>(0.0);",
    "    out.color = vec4<f32>(0.0);",
    "    return out;",
    "  }",
    "  let life = age / record.lifetime;",
    "  let t = age;",
    "  let g = shaderUniforms.gravity;",
    "  var p: vec3<f32>;",
    "  var v: vec3<f32>;",
  );
  if (forces.drag > 0) {
    lines.push(
      "  {",
      "    let inverse = 1.0 / DRAG;",
      "    let e = exp(-DRAG * t);",
      "    let a = record.velocity - g * inverse;",
      "    let settle = (1.0 - e) * inverse;",
      "    p = record.position + a * settle + g * inverse * t;",
      "    v = a * e + g * inverse;",
      "  }",
    );
  } else {
    lines.push("  p = record.position + record.velocity * t + g * (0.5 * t * t);", "  v = record.velocity + g * t;");
  }
  if (forces.orbit !== null) {
    lines.push(
      "  {",
      "    let angle = ORBIT_SPEED * DEG_TO_RAD * t;",
      "    p = shaderUniforms.orbitCenter + rotateAbout(p - shaderUniforms.orbitCenter, ORBIT_AXIS, angle);",
      "    v = rotateAbout(v, ORBIT_AXIS, angle);",
      "  }",
    );
  }
  if (forces.noise !== null) {
    const influence = lookup.noise === null ? "NOISE_INFLUENCE" : decodeRow("NOISE", "r");
    lines.push(
      "  {",
      `    let amount = NOISE_STRENGTH * ${influence};`,
      "    p += amount * noise3(p * NOISE_FREQUENCY + NOISE_SCROLL * t);",
      "  }",
    );
  }
  if (main.simulationSpace === "local") {
    lines.push(
      "  p = (shaderUniforms.emitterWorld * vec4<f32>(p, 1.0)).xyz;",
      "  v = (shaderUniforms.emitterWorld * vec4<f32>(v, 0.0)).xyz;",
    );
  }
  lines.push("  let units = vec3<f32>(pcg3d(vec3<u32>(record.seed, SALT_Y, SALT_Z))) * UNIT_SCALE;");
  lines.push(
    start.color.kind === "random"
      ? "  var rgba = mix(START_COLOR_MIN, START_COLOR_MAX, units.x);"
      : "  var rgba = START_COLOR;",
  );
  if (lookup.color !== null) {
    lines.push("  rgba *= lookupRow(COLOR_ROW, life);");
  }
  lines.push("  out.color = vec4<f32>(srgbToLinear(rgba.rgb), rgba.a);");
  lines.push("  var size = vec3<f32>(record.size) * SIZE_SCALE;");
  if (lookup.size !== null) {
    lines.push("  size *= SIZE_MIN + lookupRow(SIZE_ROW, life).rgb * (SIZE_MAX - SIZE_MIN);");
  }
  const rotation = overLifetime.rotation;
  let angular = "0.0";
  if (rotation !== null) {
    angular = rotation.kind === "curve" ? decodeRow("ROTATION", "r") : pickScalar(rotation, "units.y");
  }
  lines.push(`  let rotation = record.rotation + ${angular} * DEG_TO_RAD * t;`);
  lines.push(...orientation(renderer.mode, renderer.lit));
  lines.push(...sheetUv(definition));
  lines.push("  return out;", "}");
  return lines.join("\n");
}

/**
 * The lines that place the vertex in the world for a render mode and write `out.position`.
 *
 * @param mode - The render mode.
 * @param lit - Whether the light uniforms are declared.
 * @returns The lines.
 */
function orientation(mode: ParticleDefinition["renderer"]["mode"], lit: boolean): string[] {
  const lines: string[] = [
    "  let view = shaderSystem.view;",
    "  let viewRight = vec3<f32>(view[0].x, view[1].x, view[2].x);",
    "  let viewUp = vec3<f32>(view[0].y, view[1].y, view[2].y);",
    "  let viewForward = vec3<f32>(view[0].z, view[1].z, view[2].z);",
  ];
  if (mode === "mesh") {
    lines.push(
      "  let spin = normalize(vec3<f32>(pcg3d(vec3<u32>(record.seed, SALT_Z, SALT_Y))) * UNIT_SCALE * 2.0 - vec3<f32>(1.0));",
      "  let world = p + rotateAbout(input.position * size, spin, rotation);",
    );
    if (lit) {
      lines.push("  let normal = rotateAbout(input.normal, spin, rotation);");
    }
  } else {
    lines.push("  let corner = input.position.xy - PIVOT;");
    if (mode === "stretched") {
      lines.push(
        "  let speed = length(v);",
        "  var axis = viewUp;",
        "  if (speed > 1e-6) { axis = v / speed; }",
        "  var right = cross(viewForward, axis);",
        "  if (dot(right, right) < 1e-8) { right = viewRight; } else { right = normalize(right); }",
        "  let stretched = size.y * LENGTH_SCALE + speed * SPEED_SCALE;",
        "  let world = p + right * (corner.x * size.x) + axis * (corner.y * stretched);",
      );
      if (lit) {
        lines.push("  let normal = -viewForward;");
      }
    } else {
      lines.push(
        "  let cr = cos(rotation);",
        "  let sr = sin(rotation);",
        "  let spun = vec2<f32>(corner.x * cr - corner.y * sr, corner.x * sr + corner.y * cr);",
      );
      lines.push(...billboardBasis(mode, lit));
      lines.push("  let world = p + right * (spun.x * size.x) + up * (spun.y * size.y);");
    }
  }
  if (lit) {
    lines.push(
      "  {",
      "    let n = normalize(normal);",
      "    let lambert = max(dot(n, -shaderUniforms.mainLightDirection), 0.0);",
      "    out.color = vec4<f32>(out.color.rgb * (shaderUniforms.mainLightColor * lambert + shaderUniforms.ambientColor), out.color.a);",
      "  }",
    );
  }
  lines.push("  out.position = shaderSystem.viewProjection * vec4<f32>(world, 1.0);");
  return lines;
}

/**
 * The `right`, `up` and (for a lit definition) `normal` of a quad that is not stretched.
 *
 * @param mode - The render mode; never `"mesh"` or `"stretched"`.
 * @param lit - Whether the light uniforms are declared.
 * @returns The lines.
 */
function billboardBasis(mode: ParticleDefinition["renderer"]["mode"], lit: boolean): string[] {
  if (mode === "horizontal") {
    return [
      "  let right = vec3<f32>(1.0, 0.0, 0.0);",
      "  let up = vec3<f32>(0.0, 0.0, 1.0);",
      ...(lit ? ["  let normal = vec3<f32>(0.0, 1.0, 0.0);"] : []),
    ];
  }
  if (mode === "vertical") {
    return [
      "  let up = vec3<f32>(0.0, 1.0, 0.0);",
      "  let toCamera = shaderSystem.cameraPosition - p;",
      "  let level = vec3<f32>(toCamera.x, 0.0, toCamera.z);",
      "  var facing = vec3<f32>(0.0, 0.0, -1.0);",
      "  if (dot(level, level) > 1e-8) { facing = normalize(level); }",
      "  let right = normalize(cross(up, facing));",
      ...(lit ? ["  let normal = facing;"] : []),
    ];
  }
  return ["  let right = viewRight;", "  let up = viewUp;", ...(lit ? ["  let normal = -viewForward;"] : [])];
}

/**
 * The lines that write `out.uv`, remapped into a sprite-sheet frame when the definition has one.
 *
 * @param definition - The definition.
 * @returns The lines.
 */
function sheetUv(definition: ParticleDefinition): string[] {
  const sheet = definition.renderer.sheet;
  if (sheet === null) {
    return ["  out.uv = input.uv;"];
  }
  let frame: string;
  if (sheet.mode === "random") {
    frame = "min(SHEET_COUNT - 1.0, floor(units.z * SHEET_COUNT))";
  } else if (sheet.mode === "fps") {
    frame = "floor(units.z * SHEET_COUNT + SHEET_FPS * t) % SHEET_COUNT";
  } else {
    const fraction = definition.lookup.frame === null ? "0.0" : decodeRow("FRAME", "r");
    frame = `clamp(floor(${fraction} * SHEET_COUNT), 0.0, SHEET_COUNT - 1.0)`;
  }
  return [
    `  let frame = ${frame};`,
    "  let tile = vec2<f32>(frame % SHEET_TILES.x, floor(frame / SHEET_TILES.x));",
    "  let flipped = vec2<f32>(input.uv.x, 1.0 - input.uv.y);",
    "  let sheetUv = (flipped + tile) / SHEET_TILES;",
    "  out.uv = vec2<f32>(sheetUv.x, 1.0 - sheetUv.y);",
  ];
}

/**
 * The fragment stage: the sheet texel or a procedural soft disc, times the vertex colour, written
 * straight or premultiplied to match the blend state.
 *
 * @param definition - The definition.
 * @returns The `mainFragment` function.
 */
function fragmentStage(definition: ParticleDefinition): string {
  const { renderer } = definition;
  const lines: string[] = ["@fragment fn mainFragment(input: VertexOutput) -> @location(0) vec4<f32> {"];
  if (renderer.texture !== null) {
    lines.push("  let texel = textureSample(sheet, sheetSampler, input.uv);");
  } else if (renderer.mode === "mesh") {
    lines.push("  let texel = vec4<f32>(1.0);");
  } else {
    lines.push(
      "  let d = length(input.uv * 2.0 - vec2<f32>(1.0));",
      "  let mask = clamp(1.0 - d, 0.0, 1.0);",
      "  let texel = vec4<f32>(1.0, 1.0, 1.0, mask * mask);",
    );
  }
  lines.push("  let color = input.color * texel;");
  if (renderer.blend === "premultiplied") {
    lines.push("  return vec4<f32>(color.rgb * color.a, color.a);");
  } else {
    lines.push("  return color;");
  }
  lines.push("}");
  return lines.join("\n");
}

/**
 * The `data:` address the generated program is published under, so the core shader loader — the
 * only path that also loads core's shader adapter — reads it with no file and no network. Two
 * definitions that generate the same program share one address, and so one `ShaderAsset`.
 *
 * @param source - The generated WGSL, which is ASCII.
 * @returns A `data:text/plain;base64,…` URL.
 *
 * @beta
 */
export function particleShaderAddress(source: string): string {
  return `data:text/plain;base64,${btoa(source)}`;
}
