/**
 * `ignifx` public barrel: the umbrella entry point that re-exports `@ignifx/core` and, as each
 * phase lands, the standard extensions (`docs/architecture/00-overview.md` §2). Every symbol is
 * re-exported by name — no `export *` (coding standards §4).
 *
 * Only the core surface exists today. The input, physics, physics-2d, audio, 2d, 3d, and ui
 * re-exports and the one-call `createGame()` arrive with the phases of
 * `docs/plan/engineering-plan.md` that populate those packages.
 *
 * @packageDocumentation
 */

export {
  type App,
  type AppLiteHandles,
  applyInit,
  approximately,
  type AppSettings,
  array,
  type ArrayFieldSpec,
  assertNever,
  asset,
  type AssetFieldSpec,
  type AssetRefValue,
  type AssetTypeToken,
  bool,
  type BoolFieldSpec,
  canonicalizeNumber,
  clamp,
  clamp01,
  type Clock,
  Color,
  color,
  type ColorFieldSpec,
  type ColorLike,
  Component,
  type ComponentClassInfo,
  type ComponentDefinition,
  type ComponentHandle,
  type ComponentHooks,
  type ComponentInit,
  componentRef,
  type ComponentRefFieldSpec,
  ComponentRegistry,
  type ComponentStatics,
  type ComponentType,
  type ComponentTypeToken,
  type ConcreteComponentType,
  type ConnectOptions,
  type ConsoleLike,
  type ConsoleSinkOptions,
  CORE_ERROR_MESSAGES,
  CoreErrorCode,
  coreExtension,
  type Coroutine,
  type CoroutineHandle,
  type CoroutineHost,
  type CoroutineYield,
  createApp,
  type CreateAppOptions,
  createConsoleSink,
  createCryptoRandom,
  createDefaults,
  createDiagnosticsGroup,
  type CreateEntityOptions,
  createErrorCodeRegistry,
  createFrameSample,
  createLayerTable,
  createLogger,
  createManualClock,
  createMemorySink,
  createPerformanceClock,
  createSeededRandom,
  createServiceKey,
  createUlidFactory,
  curve,
  type CurveFieldSpec,
  type CurveKey,
  type CurveValue,
  custom,
  type CustomFieldCodec,
  type CustomFieldSpec,
  decodeProps,
  type DecodeResult,
  decodeValue,
  DEFAULT_LAYER,
  DEFAULT_MEMORY_SINK_LIMIT,
  type DeferredQueue,
  defineExtension,
  defineSchema,
  DEG_TO_RAD,
  degToRad,
  deltaAngleDegrees,
  describeSchema,
  Diagnostics,
  type DiagnosticsGroup,
  type DiagnosticsOptions,
  type Disconnect,
  encodeProps,
  encodeValue,
  Entity,
  type EntityHandle,
  entityRef,
  type EntityRefFieldSpec,
  type EnumFieldSpec,
  enumOf,
  EPSILON,
  type ErrorCode,
  type ErrorCodeDescription,
  type ErrorCodeRegistry,
  type ErrorContext,
  type ErrorFormatMode,
  ErrorRange,
  type ErrorReport,
  type Extension,
  type ExtensionContext,
  f32,
  f64,
  type FieldDefinition,
  FieldKind,
  type FieldOptions,
  type FieldsOf,
  type FieldSpec,
  formatErrorMessage,
  FRAME_HISTORY_LENGTH,
  type FrameSample,
  type FrameState,
  generateUlid,
  i32,
  IgnifxError,
  type IgnifxErrorOptions,
  INVALID_HANDLE,
  inverseLerp,
  isIgnifxError,
  isUlid,
  isValidErrorCode,
  isValidLayer,
  isWebGpuAvailable,
  type JsonArray,
  type JsonObject,
  type JsonSchemaObject,
  type JsonValue,
  LayerMask,
  layerMask,
  type LayerMaskFieldSpec,
  type LayersSettings,
  LayerTable,
  lerp,
  lerpAngleDegrees,
  type LiteEngine,
  type LiteScene,
  LOG_LEVEL_SEVERITY,
  type Logger,
  type LoggerOptions,
  LogLevel,
  type LogRecord,
  type LogSink,
  type LogThreshold,
  type ManualClock,
  map,
  type MapFieldSpec,
  Mat4,
  MAT4_IDENTITY,
  type Mat4Elements,
  type Mat4Like,
  MAX_LAYERS,
  MAX_ULID_TIME_MS,
  type MemorySink,
  moveTowards,
  type MutableQuat,
  type MutableVec2,
  type MutableVec3,
  type MutableVec4,
  type NumberFieldSpec,
  optional,
  type OptionalFieldSpec,
  type PartialFieldsOf,
  Phase,
  PHASE_COUNT,
  PHASE_NAMES,
  type PhaseIndex,
  PHASES,
  pingPong,
  type PlatformInfo,
  type PlatformKind,
  type ProfileScope,
  Quat,
  quat,
  QUAT_IDENTITY,
  type QuatLike,
  RAD_TO_DEG,
  radToDeg,
  type RandomSource,
  record,
  type RecordFieldSpec,
  type ReferenceDecoder,
  type ReferenceEncoder,
  type RegisterComponentOptions,
  type RegisterSystemOptions,
  type RenderSurface,
  repeat,
  RESERVED_LAYER_NAMES,
  resetFrameSample,
  SceneInstance,
  type Schema,
  type SchemaDescription,
  type SchemaDescriptionMeta,
  type SchemaFieldDescription,
  type SchemaIssue,
  SchemaIssueCode,
  Script,
  type ScriptCallbacks,
  type ScriptClassInfo,
  type ScriptDefinition,
  type ScriptStatics,
  type ServiceClassKey,
  type ServiceKey,
  type ServiceNameKey,
  type ServiceRegistry,
  type SetParentOptions,
  type SettingsInput,
  sign,
  Signal,
  type SignalHandler,
  type SignalLike,
  type SignalOptions,
  type SignalOwner,
  smoothStep,
  type SortingLayersSettings,
  str,
  type StringFieldSpec,
  type System,
  type SystemContext,
  TagSet,
  THIRD_PARTY_ERROR_PREFIX,
  type Time,
  type TimeSettings,
  toJsonSchema,
  Transform,
  u32,
  type UlidFactoryOptions,
  validateProps,
  validateValue,
  Vec2,
  vec2,
  VEC2_ONE,
  VEC2_ZERO,
  type Vec2Like,
  Vec3,
  vec3,
  VEC3_BACKWARD,
  VEC3_DOWN,
  VEC3_FORWARD,
  VEC3_LEFT,
  VEC3_ONE,
  VEC3_RIGHT,
  VEC3_UP,
  VEC3_ZERO,
  type Vec3Like,
  Vec4,
  vec4,
  type Vec4Like,
  type VectorFieldSpec,
  VERSION,
  waitFixedUpdate,
  type WaitInstruction,
  waitSeconds,
  waitSecondsRealtime,
  waitUntil,
  waitWhile,
  World,
  wrapAngleDegrees,
} from "@ignifx/core";
