/**
 * `ignifx` public barrel: the umbrella entry point that re-exports `@ignifx/core` and, as each
 * phase lands, the standard extensions (`docs/architecture/00-overview.md` §2). Every symbol is
 * re-exported by name — no `export *` (coding standards §4).
 *
 * Phase 2 added the render components, the GPU asset loaders, and the scene serialization surface;
 * Phase 3 adds the whole of `@ignifx/input`. The physics, physics-2d, audio, 2d, 3d, and ui
 * re-exports and the one-call `createGame()` arrive with the phases of
 * `docs/plan/engineering-plan.md` that populate those packages.
 *
 * Two `@ignifx/input` exports are deliberately **not** re-exported, because `@ignifx/core` already
 * owns the name: `VERSION` (the umbrella reports the core version) and `describeSchemas` (the
 * documentation harness reads each package's own entry point, so nothing is lost). Reach them as
 * `@ignifx/input`'s own exports when a tool needs them.
 *
 * @packageDocumentation
 */

export {
  type App,
  type AppLiteHandles,
  applyInit,
  approximately,
  type AppSettings,
  array,
  type ArrayFieldSpec,
  assertNever,
  assertSceneDependenciesLoaded,
  asset,
  ASSET_DIAGNOSTICS_COUNTERS,
  ASSET_DIAGNOSTICS_GROUP,
  ASSET_MANIFEST_FORMAT,
  ASSET_MANIFEST_VERSION,
  type AssetFieldSpec,
  type AssetHandle,
  type AssetLoader,
  AssetLoadError,
  type AssetLoadErrorOptions,
  type AssetManifest,
  type AssetManifestEntry,
  type AssetProgress,
  assetRef,
  type AssetRef,
  type AssetRefValue,
  type Assets,
  type AssetsSettings,
  type AssetState,
  type AssetTypeDefinition,
  type AssetTypeToken,
  type BatchHandle,
  binaryAssetLoader,
  type BloomEffectSettings,
  bool,
  type BoolFieldSpec,
  type BoxMeshOptions,
  Camera,
  type CameraProjection,
  canonicalizeNumber,
  CANVAS_ALPHA_MODES,
  type CanvasAlphaMode,
  type CapsuleMeshOptions,
  clamp,
  clamp01,
  type Clock,
  Color,
  color,
  type ColorFieldSpec,
  type ColorLike,
  Component,
  type ComponentClassInfo,
  type ComponentDefinition,
  type ComponentHandle,
  type ComponentHooks,
  type ComponentInit,
  componentRef,
  type ComponentRefFieldSpec,
  ComponentRegistry,
  type ComponentStatics,
  type ComponentType,
  type ComponentTypeToken,
  computeSceneHash,
  type ConcreteComponentType,
  type ConnectOptions,
  type ConsoleLike,
  type ConsoleSinkOptions,
  CORE_ERROR_MESSAGES,
  CoreErrorCode,
  coreExtension,
  type Coroutine,
  type CoroutineHandle,
  type CoroutineHost,
  type CoroutineYield,
  createApp,
  type CreateAppOptions,
  createAssetManifest,
  createConsoleSink,
  createCryptoRandom,
  createDefaults,
  createDiagnosticsGroup,
  type CreateEntityOptions,
  createEnvironmentLoader,
  createErrorCodeRegistry,
  createFontLoader,
  createFrameSample,
  createLayerTable,
  createLogger,
  createManualClock,
  createMaterialAsset,
  createMaterialLoader,
  createMemorySink,
  createModelLoader,
  createPerformanceClock,
  createRay,
  createSceneAsset,
  createSceneLoader,
  createSeededRandom,
  createServiceKey,
  createTextureLoader,
  createUlidFactory,
  curve,
  type CurveFieldSpec,
  type CurveKey,
  type CurveValue,
  custom,
  type CustomFieldCodec,
  type CustomFieldSpec,
  type CylinderMeshOptions,
  decodeProps,
  type DecodeResult,
  decodeValue,
  DEFAULT_ASSET_CONCURRENCY,
  DEFAULT_ASSET_ROOT,
  DEFAULT_BRDF_LUT_ADDRESS,
  DEFAULT_LAYER,
  DEFAULT_MEMORY_SINK_LIMIT,
  defaultRenderingSettings,
  type DeferredQueue,
  defineExtension,
  defineSchema,
  DEG_TO_RAD,
  degToRad,
  deltaAngleDegrees,
  describeEnvironmentFileFormat,
  describeMaterialFileFormat,
  describeSceneFileFormat,
  describeSchema,
  describeSchemas,
  Diagnostics,
  type DiagnosticsGroup,
  type DiagnosticsOptions,
  type Disconnect,
  EMPTY_ASSET_MANIFEST,
  encodeProps,
  encodeValue,
  Entity,
  type EntityHandle,
  type EntityOverrideField,
  entityRef,
  type EntityRefFieldSpec,
  type EnumFieldSpec,
  enumOf,
  Environment,
  ENVIRONMENT_ASSET_TYPE,
  ENVIRONMENT_FILE_EXTENSION,
  ENVIRONMENT_FILE_EXTENSIONS,
  ENVIRONMENT_FILE_FORMAT,
  ENVIRONMENT_FORMAT_VERSION,
  EnvironmentAsset,
  type EnvironmentAssetLiteHandles,
  environmentDefinition,
  type EnvironmentDefinition,
  type EnvironmentFogMode,
  type EnvironmentFogSettings,
  EPSILON,
  type ErrorCode,
  type ErrorCodeDescription,
  type ErrorCodeRegistry,
  type ErrorContext,
  type ErrorFormatMode,
  ErrorRange,
  type ErrorReport,
  type Extension,
  type ExtensionContext,
  f32,
  f64,
  type FetchLike,
  type FieldDefinition,
  FieldKind,
  type FieldOptions,
  type FieldsOf,
  type FieldSpec,
  FONT_ASSET_TYPE,
  FONT_FILE_EXTENSIONS,
  FontAsset,
  type FontAssetLiteHandles,
  formatErrorMessage,
  FRAME_HISTORY_LENGTH,
  type FrameSample,
  type FrameState,
  generateUlid,
  type GroundMeshOptions,
  i32,
  IgnifxError,
  type IgnifxErrorOptions,
  type ImageProcessingEffectSettings,
  type ImageProcessingSettings,
  instantiateScene,
  type InstantiateSceneOptions,
  INVALID_HANDLE,
  inverseLerp,
  isAssetRef,
  isIgnifxError,
  isSceneFileHeader,
  isUlid,
  isValidErrorCode,
  isValidLayer,
  isWebGpuAvailable,
  type JsonArray,
  jsonAssetLoader,
  type JsonObject,
  type JsonSchemaObject,
  type JsonValue,
  LayerMask,
  layerMask,
  type LayerMaskFieldSpec,
  type LayersSettings,
  LayerTable,
  lerp,
  lerpAngleDegrees,
  Light,
  type LightShadowSettings,
  type LightType,
  type LiteCamera,
  type LiteEngine,
  type LiteLight,
  type LiteScene,
  type LiteShadowGenerator,
  type LoaderContext,
  type LoadOptions,
  LOG_LEVEL_SEVERITY,
  type Logger,
  type LoggerOptions,
  LogLevel,
  type LogRecord,
  type LogSink,
  type LogThreshold,
  type ManualClock,
  map,
  type MapFieldSpec,
  Mat4,
  MAT4_IDENTITY,
  type Mat4Elements,
  type Mat4Like,
  MATERIAL_ALPHA_MODE_NAMES,
  MATERIAL_ASSET_TYPE,
  MATERIAL_FILE_EXTENSION,
  MATERIAL_FILE_FORMAT,
  MATERIAL_FORMAT_VERSION,
  MATERIAL_KINDS,
  type MaterialAlphaModeName,
  MaterialAsset,
  type MaterialAssetLiteHandles,
  type MaterialDefinition,
  type MaterialKind,
  MAX_LAYERS,
  MAX_ULID_TIME_MS,
  type MemorySink,
  MESH_ASSET_TYPE,
  MeshAsset,
  type MeshAssetLiteHandles,
  type MeshGeometryData,
  MeshRenderer,
  Model,
  MODEL_ASSET_TYPE,
  MODEL_FILE_EXTENSIONS,
  ModelAsset,
  type ModelAssetLiteHandles,
  type ModelInstantiation,
  moveTowards,
  type MutableQuat,
  type MutableVec2,
  type MutableVec3,
  type MutableVec4,
  type NumberFieldSpec,
  optional,
  type OptionalFieldSpec,
  type OverridePath,
  parseOverridePath,
  type PartialFieldsOf,
  PBR_TEXTURE_SLOTS,
  pbrMaterialDefinition,
  type PbrMaterialDefinition,
  Phase,
  PHASE_COUNT,
  PHASE_NAMES,
  type PhaseIndex,
  PHASES,
  pingPong,
  type PlaneMeshOptions,
  type PlatformInfo,
  type PlatformKind,
  PostProcessStack,
  type ProfileScope,
  Quat,
  quat,
  QUAT_IDENTITY,
  type QuatLike,
  RAD_TO_DEG,
  radToDeg,
  type RandomSource,
  type Ray,
  type RayVector,
  record,
  type RecordFieldSpec,
  type ReferenceDecoder,
  type ReferenceEncoder,
  type RegisterAssetOptions,
  type RegisterComponentOptions,
  type RegisterSystemOptions,
  RENDER_DIAGNOSTICS_COUNTERS,
  RENDER_DIAGNOSTICS_GROUP,
  type RenderCapture,
  type Renderer,
  RENDERING_SETTINGS_SECTION,
  type RenderingFeature,
  type RenderingFeatureSettings,
  type RenderingSettings,
  type RenderPick,
  type RenderPickOptions,
  type RenderSurface,
  type RenderTaskTiming,
  type RenderTaskTimings,
  repeat,
  RESERVED_LAYER_NAMES,
  resetFrameSample,
  SCENE_ASSET_TYPE,
  SCENE_FILE_EXTENSIONS,
  SCENE_FILE_FORMAT,
  SCENE_FORMAT_VERSION,
  type SceneAsset,
  type SceneBuildResult,
  type SceneFile,
  type SceneFileAssetRef,
  type SceneFileComponent,
  type SceneFileEntity,
  type SceneFileInstance,
  type SceneFileIssue,
  sceneFileJsonSchema,
  type SceneFileOverride,
  type SceneFileTransform,
  SceneInstance,
  type SceneLoaderOptions,
  type SceneLoadIssue,
  type Schema,
  type SchemaDescription,
  type SchemaDescriptionMeta,
  type SchemaFieldDescription,
  type SchemaIssue,
  SchemaIssueCode,
  Script,
  type ScriptCallbacks,
  type ScriptClassInfo,
  type ScriptDefinition,
  type ScriptStatics,
  serializeComponent,
  serializeEntity,
  type SerializeIssue,
  serializeScene,
  type SerializeSceneOptions,
  type ServiceClassKey,
  type ServiceKey,
  type ServiceNameKey,
  type ServiceRegistry,
  type SetParentOptions,
  type SettingsInput,
  type ShadowTechniqueName,
  sign,
  Signal,
  type SignalHandler,
  type SignalLike,
  type SignalOptions,
  type SignalOwner,
  type SmaaEffectSettings,
  smoothStep,
  type SortingLayersSettings,
  type SphereMeshOptions,
  STANDARD_TEXTURE_SLOTS,
  standardMaterialDefinition,
  type StandardMaterialDefinition,
  str,
  type StringFieldSpec,
  stringifySceneFile,
  type System,
  type SystemContext,
  TagSet,
  textAssetLoader,
  TEXTURE_ASSET_TYPE,
  TextureAsset,
  type TextureAssetLiteHandles,
  type TextureImportOptions,
  THIRD_PARTY_ERROR_PREFIX,
  type Time,
  type TimeSettings,
  toJsonSchema,
  type ToneMappingCurve,
  type TorusMeshOptions,
  Transform,
  u32,
  UidRemap,
  type UlidFactoryOptions,
  validateProps,
  validateSceneFile,
  validateValue,
  Vec2,
  vec2,
  VEC2_ONE,
  VEC2_ZERO,
  type Vec2Like,
  Vec3,
  vec3,
  VEC3_BACKWARD,
  VEC3_DOWN,
  VEC3_FORWARD,
  VEC3_LEFT,
  VEC3_ONE,
  VEC3_RIGHT,
  VEC3_UP,
  VEC3_ZERO,
  type Vec3Like,
  Vec4,
  vec4,
  type Vec4Like,
  type VectorFieldSpec,
  VERSION,
  waitFixedUpdate,
  type WaitInstruction,
  waitSeconds,
  waitSecondsRealtime,
  waitUntil,
  waitWhile,
  World,
  wrapAngleDegrees,
} from "@ignifx/core";

// Phase 2 game-facing types that were missing from the barrel
export type {
  AppEvents,
  DeviceLostInfo,
  AssetsCreateOptions,
  EntityPrefabLink,
  InstantiateOptions,
  LoadSceneOptions,
} from "@ignifx/core";

// Added to keep the umbrella a complete re-export of @ignifx/core
export { FOG_MODE_NAMES, LIGHT_TYPES, PROJECTIONS, SHADOW_TECHNIQUES, TONE_MAPPING_NAMES } from "@ignifx/core";
export type {
  LiteAnimationGroup,
  LiteAssetContainer,
  LiteEnvironmentTextures,
  LiteFont,
  LiteMaterial,
  LiteMesh,
  LitePbrMaterial,
  LiteSceneNode,
  LiteSkeleton,
  LiteStandardMaterial,
  LiteTexture2D,
  LoadProgress,
  MaterialAlphaMode,
} from "@ignifx/core";
export { MATERIAL_ALPHA_MODES } from "@ignifx/core";

// @ignifx/input — devices, action maps, bindings, control schemes, pointer lock, and rebinding.
export {
  type ActionDefinition,
  ActionMap,
  type ActionMapDefinition,
  type ActionSetOptions,
  ActionVector,
  ANY_KEY_CONTROL,
  applyOverrides,
  applyProcessors,
  Binding,
  type BindingContext,
  type BindingDefinition,
  type BindingResolver,
  buildControls,
  clearOverrides,
  collectOverrides,
  compositeIsVector,
  CompositeKind,
  compositeParts,
  type ControlDescriptor,
  ControlKind,
  controlPath,
  type ControlRef,
  type ControlSchemeDefinition,
  ControlSchemes,
  controlSlotCount,
  type ControlSpec,
  type ControlTouchHandler,
  type ControlValue,
  createInputActionsLoader,
  createKeyboardDevice,
  createMouseDevice,
  createNavigatorGamepadReader,
  createPointerDevice,
  createTouchDevice,
  Cursor,
  defaultInputSettings,
  defineInputActions,
  describeInputActionsFormat,
  describeInputSchemas,
  DEVICE_KINDS,
  DeviceKind,
  type DomSource,
  type DomTarget,
  GAMEPAD_REMAPS,
  GAMEPAD_SLOTS,
  gamepadControlNames,
  GamepadDevice,
  type GamepadLike,
  type GamepadReader,
  type GamepadRemap,
  type GamepadSnapshot,
  input,
  INPUT_ACTIONS_ASSET_TYPE,
  INPUT_ACTIONS_FILE_EXTENSIONS,
  INPUT_ACTIONS_FORMAT,
  INPUT_ACTIONS_FORMAT_VERSION,
  INPUT_DIAGNOSTICS_COUNTERS,
  INPUT_DIAGNOSTICS_GROUP,
  INPUT_ERROR_MESSAGES,
  INPUT_OVERRIDES_FORMAT,
  INPUT_OVERRIDES_FORMAT_VERSION,
  INPUT_RESOLVE_ORDER,
  INPUT_SETTINGS_SECTION,
  InputAction,
  type InputActionEvent,
  InputActionsAsset,
  type InputActionsDefinition,
  InputActionSet,
  type InputActionSignal,
  type InputActionsInput,
  inputActionsJsonSchema,
  InputActionsView,
  type InputActionType,
  InputDevice,
  InputDevices,
  inputError,
  InputErrorCode,
  type InputErrorOptions,
  type InputEventRecord,
  type InputEventType,
  type InputOptions,
  type InputOverrideEntry,
  type InputOverridesJson,
  InputService,
  type InputServiceOptions,
  type InputSettings,
  inputSettingsSchema,
  type InteractiveRebindOptions,
  type InteractiveRebindResult,
  keyboardControlNames,
  keyCodeControlNames,
  mouseControlNames,
  parseComposite,
  parseControlPath,
  type ParsedControlPath,
  parseProcessor,
  parseProcessors,
  pinToDeviceSlot,
  PlayerInput,
  PointerLock,
  type PointerLockSettings,
  type Processor,
  ProcessorKind,
  resolveGamepadRemap,
  type SimulatedEvent,
  type SimulatedValue,
  TOUCH_SLOTS,
  touchControlNames,
  validateInputActions,
  type VibrationActuatorLike,
  type VibrationEffectParameters,
  VirtualDevice,
} from "@ignifx/input";

// Kernel hooks for extension authors (Phase 4 preparation)
export { PhysicsCallbackName, ScriptCallbackKind } from "@ignifx/core";
export type { WorldLiteHandles } from "@ignifx/core";

// @ignifx/audio — buses, AudioSource/AudioListener/MusicPlayer, spatial audio, unlock flow.
// `VERSION` and `describeSchemas` are deliberately absent: those names belong to @ignifx/core here.
export {
  AUDIO_ASSET_TYPE,
  AUDIO_BUSES_ASSET_TYPE,
  AUDIO_BUSES_FILE_EXTENSION,
  AUDIO_BUSES_FORMAT,
  AUDIO_BUSES_FORMAT_VERSION,
  AUDIO_DIAGNOSTICS_COUNTERS,
  AUDIO_DIAGNOSTICS_GROUP,
  AUDIO_DISTANCE_MODELS,
  AUDIO_ERROR_MESSAGES,
  AUDIO_FILE_EXTENSIONS,
  AUDIO_PUMP_ORDER,
  AUDIO_SETTINGS_SECTION,
  AudioBusesAsset,
  AudioClip,
  AudioErrorCode,
  AudioListener,
  AudioService,
  AudioSource,
  DEFAULT_AUDIO_BUSES,
  DEFAULT_PAUSABLE_BUSES,
  DEFAULT_SOUND_BUS,
  HeadlessBackend,
  HeadlessBus,
  HeadlessSound,
  MusicPlayer,
  SoundVoice,
  WebAudioBackend,
  audio,
  audioError,
  audioSettingsSchema,
  createAudioBusesLoader,
  createAudioClipLoader,
  createWebAudioBackend,
  defaultAudioSettings,
  describeAudioBusesFormat,
  parseAudioBusesFile,
  parseWavHeader,
  type AudioBackend,
  type AudioBackendContext,
  type AudioBackendKind,
  type AudioBackendState,
  type AudioBus,
  type AudioBusDefinition,
  type AudioClipInit,
  type AudioClipLiteHandles,
  type AudioClipLoaderOptions,
  type AudioConeSettings,
  type AudioDecoder,
  type AudioDistanceModel,
  type AudioErrorOptions,
  type AudioLiteHandles,
  type AudioOptions,
  type AudioServiceLiteHandles,
  type AudioServiceOptions,
  type AudioServiceState,
  type AudioSettings,
  type BackendBus,
  type BackendBusRequest,
  type BackendPlayRequest,
  type BackendSound,
  type BackendSoundRequest,
  type BackendSpatialRequest,
  type CreateBusOptions,
  type HeadlessBackendOptions,
  type LiteAudioBus,
  type LiteAudioEngine,
  type LiteSoundBuffer,
  type LiteSpatialTarget,
  type LiteStaticSound,
  type LiteStreamingSound,
  type MusicPlayOptions,
  type MusicStopOptions,
  type OneShotOptions,
  type OneShotVolume,
  type PlayOptions,
  type SoundInstance,
  type VoiceHost,
  type VoiceRequest,
  type WavHeader,
} from "@ignifx/audio";

// @ignifx/physics — Havok rigid bodies, colliders, triggers, CharacterController, layer matrix, queries.
// `describeSchemas` is deliberately absent: that name belongs to @ignifx/core here.
export {
  BODY_TYPES,
  BoxCollider,
  CAPSULE_DIRECTIONS,
  COLLISION_EVENT_MODES,
  COLLISION_IDENTITY_MODES,
  CapsuleCollider,
  CharacterController,
  Collider,
  CylinderCollider,
  HAVOK_WASM_AUTO,
  HeightfieldCollider,
  INTERPOLATION_MODES,
  KINEMATIC_SYNC_MODES,
  MeshCollider,
  PHYSICS_DIAGNOSTICS_COUNTERS,
  PHYSICS_DIAGNOSTICS_GROUP,
  PHYSICS_ERROR_MESSAGES,
  PHYSICS_MATERIAL_ASSET_TYPE,
  PHYSICS_MATERIAL_FILE_EXTENSION,
  PHYSICS_MATERIAL_FILE_FORMAT,
  PHYSICS_MATERIAL_FORMAT_VERSION,
  PHYSICS_SETTINGS_SECTION,
  PhysicsErrorCode,
  PhysicsMaterial,
  PhysicsService,
  Rigidbody,
  SUPPORT_STATES,
  SphereCollider,
  colliderFields,
  createPhysicsMaterialLoader,
  defaultPhysicsSettings,
  describePhysicsMaterialFileFormat,
  parsePhysicsMaterial,
  physics,
  physicsError,
  physicsSettingsSchema,
  type BodyType,
  type CapsuleDirection,
  type CharacterCollision,
  type Collision,
  type CollisionEventMode,
  type CollisionIdentityMode,
  type ContactPoint,
  type FreezeRotation,
  type InterpolationMode,
  type KinematicSyncMode,
  type PhysicsDebugViewer,
  type PhysicsErrorOptions,
  type PhysicsLiteHandles,
  type PhysicsMaterialValues,
  type PhysicsOptions,
  type PhysicsSettings,
  type QueryOptions,
  type QueryShape,
  type RaycastHit,
  type RigidbodyLiteHandles,
  type ShapeCastHit,
  type SupportStateName,
  type TriggerEvent,
  type VelocityLimitSettings,
} from "@ignifx/physics";
