/**
 * `ignifx` public barrel: the umbrella entry point that re-exports `@ignifx/core` and, as each
 * phase lands, the standard extensions (`docs/architecture/00-overview.md` §2). Every symbol is
 * re-exported by name — no `export *` (coding standards §4).
 *
 * Phase 2 added the render components, the GPU asset loaders, and the scene serialization surface;
 * Phase 3 adds the whole of `@ignifx/input`. The physics, physics-2d, audio, 2d, 3d, and ui
 * re-exports and the one-call `createGame()` arrive with the phases of
 * `docs/plan/engineering-plan.md` that populate those packages.
 *
 * Two `@ignifx/input` exports are deliberately **not** re-exported, because `@ignifx/core` already
 * owns the name: `VERSION` (the umbrella reports the core version) and `describeSchemas` (the
 * documentation harness reads each package's own entry point, so nothing is lost). Reach them as
 * `@ignifx/input`'s own exports when a tool needs them.
 *
 * @packageDocumentation
 */

export {
  type App,
  type AppLiteHandles,
  applyInit,
  approximately,
  type AppSettings,
  array,
  type ArrayFieldSpec,
  assertNever,
  assertSceneDependenciesLoaded,
  asset,
  ASSET_DIAGNOSTICS_COUNTERS,
  ASSET_DIAGNOSTICS_GROUP,
  ASSET_MANIFEST_FORMAT,
  ASSET_MANIFEST_VERSION,
  type AssetFieldSpec,
  type AssetHandle,
  type AssetLoader,
  AssetLoadError,
  type AssetLoadErrorOptions,
  type AssetManifest,
  type AssetManifestEntry,
  type AssetProgress,
  assetRef,
  type AssetRef,
  type AssetRefValue,
  type Assets,
  type AssetsSettings,
  type AssetState,
  type AssetTypeDefinition,
  type AssetTypeToken,
  type BatchHandle,
  binaryAssetLoader,
  type BloomEffectSettings,
  bool,
  type BoolFieldSpec,
  type BoxMeshOptions,
  Camera,
  type CameraProjection,
  canonicalizeNumber,
  CANVAS_ALPHA_MODES,
  type CanvasAlphaMode,
  type CapsuleMeshOptions,
  clamp,
  clamp01,
  type Clock,
  Color,
  color,
  type ColorFieldSpec,
  type ColorLike,
  Component,
  type ComponentClassInfo,
  type ComponentDefinition,
  type ComponentHandle,
  type ComponentHooks,
  type ComponentInit,
  componentRef,
  type ComponentRefFieldSpec,
  ComponentRegistry,
  type ComponentStatics,
  type ComponentType,
  type ComponentTypeToken,
  computeSceneHash,
  type ConcreteComponentType,
  type ConnectOptions,
  type ConsoleLike,
  type ConsoleSinkOptions,
  CORE_ERROR_MESSAGES,
  CoreErrorCode,
  coreExtension,
  type Coroutine,
  type CoroutineHandle,
  type CoroutineHost,
  type CoroutineYield,
  createApp,
  type CreateAppOptions,
  createAssetManifest,
  createConsoleSink,
  createCryptoRandom,
  createDefaults,
  createDiagnosticsGroup,
  type CreateEntityOptions,
  createEnvironmentLoader,
  createErrorCodeRegistry,
  createFontLoader,
  createFrameSample,
  createLayerTable,
  createLogger,
  createManualClock,
  createMaterialAsset,
  createMaterialLoader,
  createMemorySink,
  createModelLoader,
  createPerformanceClock,
  createRay,
  createSceneAsset,
  createSceneLoader,
  createSeededRandom,
  createServiceKey,
  createTextureLoader,
  createUlidFactory,
  curve,
  type CurveFieldSpec,
  type CurveKey,
  type CurveValue,
  custom,
  type CustomFieldCodec,
  type CustomFieldSpec,
  type CylinderMeshOptions,
  decodeProps,
  type DecodeResult,
  decodeValue,
  DEFAULT_ASSET_CONCURRENCY,
  DEFAULT_ASSET_ROOT,
  DEFAULT_BRDF_LUT_ADDRESS,
  DEFAULT_LAYER,
  DEFAULT_MEMORY_SINK_LIMIT,
  defaultRenderingSettings,
  type DeferredQueue,
  defineExtension,
  defineSchema,
  DEG_TO_RAD,
  degToRad,
  deltaAngleDegrees,
  describeEnvironmentFileFormat,
  describeMaterialFileFormat,
  describeSceneFileFormat,
  describeSchema,
  describeSchemas,
  Diagnostics,
  type DiagnosticsGroup,
  type DiagnosticsOptions,
  type Disconnect,
  EMPTY_ASSET_MANIFEST,
  encodeProps,
  encodeValue,
  Entity,
  type EntityHandle,
  type EntityOverrideField,
  entityRef,
  type EntityRefFieldSpec,
  type EnumFieldSpec,
  enumOf,
  Environment,
  ENVIRONMENT_ASSET_TYPE,
  ENVIRONMENT_FILE_EXTENSION,
  ENVIRONMENT_FILE_EXTENSIONS,
  ENVIRONMENT_FILE_FORMAT,
  ENVIRONMENT_FORMAT_VERSION,
  EnvironmentAsset,
  type EnvironmentAssetLiteHandles,
  environmentDefinition,
  type EnvironmentDefinition,
  type EnvironmentFogMode,
  type EnvironmentFogSettings,
  EPSILON,
  type ErrorCode,
  type ErrorCodeDescription,
  type ErrorCodeRegistry,
  type ErrorContext,
  type ErrorFormatMode,
  ErrorRange,
  type ErrorReport,
  type Extension,
  type ExtensionContext,
  f32,
  f64,
  type FetchLike,
  type FieldDefinition,
  FieldKind,
  type FieldOptions,
  type FieldsOf,
  type FieldSpec,
  FONT_ASSET_TYPE,
  FONT_FILE_EXTENSIONS,
  FontAsset,
  type FontAssetLiteHandles,
  formatErrorMessage,
  FRAME_HISTORY_LENGTH,
  type FrameSample,
  type FrameState,
  generateUlid,
  type GroundMeshOptions,
  i32,
  IgnifxError,
  type IgnifxErrorOptions,
  type ImageProcessingEffectSettings,
  type ImageProcessingSettings,
  instantiateScene,
  type InstantiateSceneOptions,
  INVALID_HANDLE,
  inverseLerp,
  isAssetRef,
  isIgnifxError,
  isSceneFileHeader,
  isUlid,
  isValidErrorCode,
  isValidLayer,
  isWebGpuAvailable,
  type JsonArray,
  jsonAssetLoader,
  type JsonObject,
  type JsonSchemaObject,
  type JsonValue,
  LayerMask,
  layerMask,
  type LayerMaskFieldSpec,
  type LayersSettings,
  LayerTable,
  lerp,
  lerpAngleDegrees,
  Light,
  type LightShadowSettings,
  type LightType,
  type LiteCamera,
  type LiteEngine,
  type LiteLight,
  type LiteScene,
  type LiteShadowGenerator,
  type LoaderContext,
  type LoadOptions,
  LOG_LEVEL_SEVERITY,
  type Logger,
  type LoggerOptions,
  LogLevel,
  type LogRecord,
  type LogSink,
  type LogThreshold,
  type ManualClock,
  map,
  type MapFieldSpec,
  Mat4,
  MAT4_IDENTITY,
  type Mat4Elements,
  type Mat4Like,
  MATERIAL_ALPHA_MODE_NAMES,
  MATERIAL_ASSET_TYPE,
  MATERIAL_FILE_EXTENSION,
  MATERIAL_FILE_FORMAT,
  MATERIAL_FORMAT_VERSION,
  MATERIAL_KINDS,
  type MaterialAlphaModeName,
  MaterialAsset,
  type MaterialAssetLiteHandles,
  type MaterialDefinition,
  type MaterialKind,
  MAX_LAYERS,
  MAX_ULID_TIME_MS,
  type MemorySink,
  MESH_ASSET_TYPE,
  MeshAsset,
  type MeshAssetLiteHandles,
  type MeshGeometryData,
  MeshRenderer,
  Model,
  MODEL_ASSET_TYPE,
  MODEL_FILE_EXTENSIONS,
  ModelAsset,
  type ModelAssetLiteHandles,
  type ModelInstantiation,
  moveTowards,
  type MutableQuat,
  type MutableVec2,
  type MutableVec3,
  type MutableVec4,
  type NumberFieldSpec,
  optional,
  type OptionalFieldSpec,
  type OverridePath,
  parseOverridePath,
  type PartialFieldsOf,
  PBR_TEXTURE_SLOTS,
  pbrMaterialDefinition,
  type PbrMaterialDefinition,
  Phase,
  PHASE_COUNT,
  PHASE_NAMES,
  type PhaseIndex,
  PHASES,
  pingPong,
  type PlaneMeshOptions,
  type PlatformInfo,
  type PlatformKind,
  PostProcessStack,
  type ProfileScope,
  Quat,
  quat,
  QUAT_IDENTITY,
  type QuatLike,
  RAD_TO_DEG,
  radToDeg,
  type RandomSource,
  type Ray,
  type RayVector,
  record,
  type RecordFieldSpec,
  type ReferenceDecoder,
  type ReferenceEncoder,
  type RegisterAssetOptions,
  type RegisterComponentOptions,
  type RegisterSystemOptions,
  RENDER_DIAGNOSTICS_COUNTERS,
  RENDER_DIAGNOSTICS_GROUP,
  type RenderCapture,
  type Renderer,
  RENDERING_SETTINGS_SECTION,
  type RenderingFeature,
  type RenderingFeatureSettings,
  type RenderingSettings,
  type RenderPick,
  type RenderPickOptions,
  type RenderSurface,
  type RenderTaskTiming,
  type RenderTaskTimings,
  repeat,
  RESERVED_LAYER_NAMES,
  resetFrameSample,
  SCENE_ASSET_TYPE,
  SCENE_FILE_EXTENSIONS,
  SCENE_FILE_FORMAT,
  SCENE_FORMAT_VERSION,
  type SceneAsset,
  type SceneBuildResult,
  type SceneFile,
  type SceneFileAssetRef,
  type SceneFileComponent,
  type SceneFileEntity,
  type SceneFileInstance,
  type SceneFileIssue,
  sceneFileJsonSchema,
  type SceneFileOverride,
  type SceneFileTransform,
  SceneInstance,
  type SceneLoaderOptions,
  type SceneLoadIssue,
  type Schema,
  type SchemaDescription,
  type SchemaDescriptionMeta,
  type SchemaFieldDescription,
  type SchemaIssue,
  SchemaIssueCode,
  Script,
  type ScriptCallbacks,
  type ScriptClassInfo,
  type ScriptDefinition,
  type ScriptStatics,
  serializeComponent,
  serializeEntity,
  type SerializeIssue,
  serializeScene,
  type SerializeSceneOptions,
  type ServiceClassKey,
  type ServiceKey,
  type ServiceNameKey,
  type ServiceRegistry,
  type SetParentOptions,
  type SettingsInput,
  type ShadowTechniqueName,
  sign,
  Signal,
  type SignalHandler,
  type SignalLike,
  type SignalOptions,
  type SignalOwner,
  type SmaaEffectSettings,
  smoothStep,
  type SortingLayersSettings,
  type SphereMeshOptions,
  STANDARD_TEXTURE_SLOTS,
  standardMaterialDefinition,
  type StandardMaterialDefinition,
  str,
  type StringFieldSpec,
  stringifySceneFile,
  type System,
  type SystemContext,
  TagSet,
  textAssetLoader,
  TEXTURE_ASSET_TYPE,
  TextureAsset,
  type TextureAssetLiteHandles,
  type TextureImportOptions,
  THIRD_PARTY_ERROR_PREFIX,
  type Time,
  type TimeSettings,
  toJsonSchema,
  type ToneMappingCurve,
  type TorusMeshOptions,
  Transform,
  u32,
  UidRemap,
  type UlidFactoryOptions,
  validateProps,
  validateSceneFile,
  validateValue,
  Vec2,
  vec2,
  VEC2_ONE,
  VEC2_ZERO,
  type Vec2Like,
  Vec3,
  vec3,
  VEC3_BACKWARD,
  VEC3_DOWN,
  VEC3_FORWARD,
  VEC3_LEFT,
  VEC3_ONE,
  VEC3_RIGHT,
  VEC3_UP,
  VEC3_ZERO,
  type Vec3Like,
  Vec4,
  vec4,
  type Vec4Like,
  type VectorFieldSpec,
  VERSION,
  waitFixedUpdate,
  type WaitInstruction,
  waitSeconds,
  waitSecondsRealtime,
  waitUntil,
  waitWhile,
  World,
  wrapAngleDegrees,
  // Tweens (Phase 7, core-owned)
  EASINGS,
  EASING_NAMES,
  TWEEN_LOOP_FOREVER,
  TWEEN_SYSTEM_ORDER,
  TWEEN_VALUE_KINDS,
  Tween,
  resolveEase,
  type EasingFunction,
  type EasingName,
  type TweenOptions,
  type TweenProps,
  type TweenTargetValue,
  type TweenValueKind,
  type TweenableValue,
  type Tweens,
  // Platform and storage (Phase 9)
  createFileStorageBackend,
  DEFAULT_STORAGE_NAMESPACE,
  IndexedDbStorageBackend,
  MemoryStorageBackend,
  NAMESPACE_SEGMENT_MAX_LENGTH,
  STORAGE_KEY_MAX_LENGTH,
  type FileStorageOptions,
  type GpuAdapterInfo,
  type PlatformOs,
  type Storage,
  type StorageBackend,
  type StoredValue,
  type StoredValueKind,
  type WebGpuInfo,
  // Hot reload (Phase 10)
  type ComponentReplacement,
  type HotReloadHost,
  type HotReloadKind,
  type HotReloadModule,
  type HotReloadOptions,
  type HotReloadPolicy,
  type HotReloadReport,
  type HotReloadStatics,
  // Scene/prefab token for `asset()` fields (Phase 11)
  SceneAssetToken,
} from "@ignifx/core";

// Phase 2 game-facing types that were missing from the barrel
export type {
  AppEvents,
  DeviceLostInfo,
  AssetsCreateOptions,
  EntityPrefabLink,
  InstantiateOptions,
  LoadSceneOptions,
} from "@ignifx/core";

// Added to keep the umbrella a complete re-export of @ignifx/core
export { FOG_MODE_NAMES, LIGHT_TYPES, PROJECTIONS, SHADOW_TECHNIQUES, TONE_MAPPING_NAMES } from "@ignifx/core";
export type {
  LiteAnimationGroup,
  LiteAssetContainer,
  LiteEnvironmentTextures,
  LiteFont,
  LiteMaterial,
  LiteMesh,
  LitePbrMaterial,
  LiteSceneNode,
  LiteSkeleton,
  LiteStandardMaterial,
  LiteTexture2D,
  LoadProgress,
  MaterialAlphaMode,
} from "@ignifx/core";
export { MATERIAL_ALPHA_MODES } from "@ignifx/core";

// @ignifx/input — devices, action maps, bindings, control schemes, pointer lock, and rebinding.
export {
  type ActionDefinition,
  ActionMap,
  type ActionMapDefinition,
  type ActionSetOptions,
  ActionVector,
  ANY_KEY_CONTROL,
  applyOverrides,
  applyProcessors,
  Binding,
  type BindingContext,
  type BindingDefinition,
  type BindingResolver,
  buildControls,
  clearOverrides,
  collectOverrides,
  compositeIsVector,
  CompositeKind,
  compositeParts,
  type ControlDescriptor,
  ControlKind,
  controlPath,
  type ControlRef,
  type ControlSchemeDefinition,
  ControlSchemes,
  controlSlotCount,
  type ControlSpec,
  type ControlTouchHandler,
  type ControlValue,
  createInputActionsLoader,
  createKeyboardDevice,
  createMouseDevice,
  createNavigatorGamepadReader,
  createPointerDevice,
  createTouchDevice,
  Cursor,
  defaultInputSettings,
  defineInputActions,
  describeInputActionsFormat,
  describeInputSchemas,
  DEVICE_KINDS,
  DeviceKind,
  type DomSource,
  type DomTarget,
  GAMEPAD_REMAPS,
  GAMEPAD_SLOTS,
  gamepadControlNames,
  GamepadDevice,
  type GamepadLike,
  type GamepadReader,
  type GamepadRemap,
  type GamepadSnapshot,
  input,
  INPUT_ACTIONS_ASSET_TYPE,
  INPUT_ACTIONS_FILE_EXTENSIONS,
  INPUT_ACTIONS_FORMAT,
  INPUT_ACTIONS_FORMAT_VERSION,
  INPUT_DIAGNOSTICS_COUNTERS,
  INPUT_DIAGNOSTICS_GROUP,
  INPUT_ERROR_MESSAGES,
  INPUT_OVERRIDES_FORMAT,
  INPUT_OVERRIDES_FORMAT_VERSION,
  INPUT_RESOLVE_ORDER,
  INPUT_SETTINGS_SECTION,
  InputAction,
  type InputActionEvent,
  InputActionsAsset,
  type InputActionsDefinition,
  InputActionSet,
  type InputActionSignal,
  type InputActionsInput,
  inputActionsJsonSchema,
  InputActionsView,
  type InputActionType,
  InputDevice,
  InputDevices,
  inputError,
  InputErrorCode,
  type InputErrorOptions,
  type InputEventRecord,
  type InputEventType,
  type InputOptions,
  type InputOverrideEntry,
  type InputOverridesJson,
  InputService,
  type InputServiceOptions,
  type InputSettings,
  inputSettingsSchema,
  type InteractiveRebindOptions,
  type InteractiveRebindResult,
  keyboardControlNames,
  keyCodeControlNames,
  mouseControlNames,
  parseComposite,
  parseControlPath,
  type ParsedControlPath,
  parseProcessor,
  parseProcessors,
  pinToDeviceSlot,
  PlayerInput,
  PointerLock,
  type PointerLockSettings,
  type Processor,
  ProcessorKind,
  resolveGamepadRemap,
  type SimulatedEvent,
  type SimulatedValue,
  TOUCH_SLOTS,
  touchControlNames,
  validateInputActions,
  type VibrationActuatorLike,
  type VibrationEffectParameters,
  VirtualDevice,
} from "@ignifx/input";

// Kernel hooks for extension authors (Phase 4 preparation)
export { PhysicsCallbackName, ScriptCallbackKind } from "@ignifx/core";
export type { WorldLiteHandles } from "@ignifx/core";

// @ignifx/audio — buses, AudioSource/AudioListener/MusicPlayer, spatial audio, unlock flow.
// `VERSION` and `describeSchemas` are deliberately absent: those names belong to @ignifx/core here.
export {
  AUDIO_ASSET_TYPE,
  AUDIO_BUSES_ASSET_TYPE,
  AUDIO_BUSES_FILE_EXTENSION,
  AUDIO_BUSES_FORMAT,
  AUDIO_BUSES_FORMAT_VERSION,
  AUDIO_DIAGNOSTICS_COUNTERS,
  AUDIO_DIAGNOSTICS_GROUP,
  AUDIO_DISTANCE_MODELS,
  AUDIO_ERROR_MESSAGES,
  AUDIO_FILE_EXTENSIONS,
  AUDIO_PUMP_ORDER,
  AUDIO_SETTINGS_SECTION,
  AudioBusesAsset,
  AudioClip,
  AudioErrorCode,
  AudioListener,
  AudioService,
  AudioSource,
  DEFAULT_AUDIO_BUSES,
  DEFAULT_PAUSABLE_BUSES,
  DEFAULT_SOUND_BUS,
  HeadlessBackend,
  HeadlessBus,
  HeadlessSound,
  MusicPlayer,
  SoundVoice,
  WebAudioBackend,
  audio,
  audioError,
  audioSettingsSchema,
  createAudioBusesLoader,
  createAudioClipLoader,
  createWebAudioBackend,
  defaultAudioSettings,
  describeAudioBusesFormat,
  parseAudioBusesFile,
  parseWavHeader,
  type AudioBackend,
  type AudioBackendContext,
  type AudioBackendKind,
  type AudioBackendState,
  type AudioBus,
  type AudioBusDefinition,
  type AudioClipInit,
  type AudioClipLiteHandles,
  type AudioClipLoaderOptions,
  type AudioConeSettings,
  type AudioDecoder,
  type AudioDistanceModel,
  type AudioErrorOptions,
  type AudioLiteHandles,
  type AudioOptions,
  type AudioServiceLiteHandles,
  type AudioServiceOptions,
  type AudioServiceState,
  type AudioSettings,
  type BackendBus,
  type BackendBusRequest,
  type BackendPlayRequest,
  type BackendSound,
  type BackendSoundRequest,
  type BackendSpatialRequest,
  type CreateBusOptions,
  type HeadlessBackendOptions,
  type LiteAudioBus,
  type LiteAudioEngine,
  type LiteSoundBuffer,
  type LiteSpatialTarget,
  type LiteStaticSound,
  type LiteStreamingSound,
  type MusicPlayOptions,
  type MusicStopOptions,
  type OneShotOptions,
  type OneShotVolume,
  type PlayOptions,
  type SoundInstance,
  type VoiceHost,
  type VoiceRequest,
  type WavHeader,
} from "@ignifx/audio";

// @ignifx/physics — Havok rigid bodies, colliders, triggers, CharacterController, layer matrix, queries.
// `describeSchemas` is deliberately absent: that name belongs to @ignifx/core here.
export {
  BODY_TYPES,
  BoxCollider,
  CAPSULE_DIRECTIONS,
  COLLISION_EVENT_MODES,
  COLLISION_IDENTITY_MODES,
  CapsuleCollider,
  CharacterController,
  Collider,
  CylinderCollider,
  HAVOK_WASM_AUTO,
  HeightfieldCollider,
  INTERPOLATION_MODES,
  KINEMATIC_SYNC_MODES,
  MeshCollider,
  PHYSICS_DIAGNOSTICS_COUNTERS,
  PHYSICS_DIAGNOSTICS_GROUP,
  PHYSICS_ERROR_MESSAGES,
  PHYSICS_MATERIAL_ASSET_TYPE,
  PHYSICS_MATERIAL_FILE_EXTENSION,
  PHYSICS_MATERIAL_FILE_FORMAT,
  PHYSICS_MATERIAL_FORMAT_VERSION,
  PHYSICS_SETTINGS_SECTION,
  PhysicsErrorCode,
  PhysicsMaterial,
  PhysicsService,
  Rigidbody,
  SUPPORT_STATES,
  SphereCollider,
  colliderFields,
  createPhysicsMaterialLoader,
  defaultPhysicsSettings,
  describePhysicsMaterialFileFormat,
  parsePhysicsMaterial,
  physics,
  physicsError,
  physicsSettingsSchema,
  type BodyType,
  type CapsuleDirection,
  type CharacterCollision,
  type Collision,
  type CollisionEventMode,
  type CollisionIdentityMode,
  type ContactPoint,
  type FreezeRotation,
  type InterpolationMode,
  type KinematicSyncMode,
  type PhysicsDebugViewer,
  type PhysicsErrorOptions,
  type PhysicsLiteHandles,
  type PhysicsMaterialValues,
  type PhysicsOptions,
  type PhysicsSettings,
  type QueryOptions,
  type QueryShape,
  type RaycastHit,
  type RigidbodyLiteHandles,
  type ShapeCastHit,
  type SupportStateName,
  type TriggerEvent,
  type VelocityLimitSettings,
} from "@ignifx/physics";

// @ignifx/physics-2d — Rapier 2D rigid bodies, colliders, triggers, CharacterController2D, 2D queries.
// `describeSchemas` is deliberately absent: that name belongs to @ignifx/core here.
export {
  BODY_TYPES_2D,
  BoxCollider2D,
  CAPSULE_2D_DIRECTIONS,
  CHARACTER_SHAPES_2D,
  COLLISION_EVENT_MODES_2D,
  COMBINE_RULES,
  CapsuleCollider2D,
  CharacterController2D,
  CircleCollider2D,
  Collider2D,
  EdgeCollider2D,
  INTERPOLATION_MODES_2D,
  PHYSICS_2D_DIAGNOSTICS_COUNTERS,
  PHYSICS_2D_DIAGNOSTICS_GROUP,
  PHYSICS_2D_ERROR_MESSAGES,
  PHYSICS_2D_SETTINGS_SECTION,
  PHYSICS_MATERIAL_2D_ASSET_TYPE,
  PHYSICS_MATERIAL_2D_FILE_EXTENSION,
  PHYSICS_MATERIAL_2D_FILE_FORMAT,
  PHYSICS_MATERIAL_2D_FORMAT_VERSION,
  Physics2DErrorCode,
  Physics2DService,
  PhysicsMaterial2D,
  PolygonCollider2D,
  Rigidbody2D,
  TilemapCollider2D,
  collider2DFields,
  createPhysicsMaterial2DLoader,
  defaultPhysics2DSettings,
  parsePhysicsMaterial2D,
  physics2DError,
  physics2DSettingsSchema,
  physics2d,
  type BodyType2D,
  type Capsule2DDirection,
  type CharacterCollision2D,
  type CharacterShape2D,
  type Collision2D,
  type CollisionEventMode2D,
  type CombineRule,
  type ContactPoint2D,
  type InterpolationMode2D,
  type Physics2DErrorOptions,
  type Physics2DMaterialValues,
  type Physics2DOptions,
  type Physics2DRapierHandles,
  type Physics2DSettings,
  type QueryOptions2D,
  type RaycastHit2D,
  type Rigidbody2DRapierHandles,
  type ShapeCastHit2D,
  type TriggerEvent2D,
} from "@ignifx/physics-2d";

// @ignifx/2d — Camera2D, sprites, sprite animation, atlases, tilemaps, sorting layers, parallax, 2D picking.
// `VERSION` and `describeSchemas` are deliberately absent: those names belong to @ignifx/core here.
export {
  Camera2D,
  Camera2DFollow,
  DEFAULT_CHUNK_SIZE,
  DEFAULT_CLIP_FPS,
  DEFAULT_ORTHOGRAPHIC_SIZE,
  DEFAULT_PIXELS_PER_UNIT,
  DEFAULT_REFERENCE_RESOLUTION,
  DEFAULT_SORTING_LAYER,
  EMPTY_TILE_ID,
  LDTK_DEFAULT_INTGRID_COLLIDERS,
  LDTK_INTGRID_TILESET_NAME,
  ParallaxLayer,
  SORTING_LAYER_ORDER_STEP,
  SPRITE_ANIMATION_ASSET_TYPE,
  SPRITE_ANIMATION_FILE_EXTENSIONS,
  SPRITE_ANIMATION_FORMAT,
  SPRITE_ANIMATION_FORMAT_VERSION,
  SPRITE_ATLAS_ASSET_TYPE,
  SPRITE_ATLAS_FILE_EXTENSIONS,
  SPRITE_ATLAS_FORMAT,
  SPRITE_ATLAS_FORMAT_VERSION,
  SPRITE_BLEND_MODES,
  SPRITE_EFFECT_KINDS,
  SPRITE_FRAME_FRAGMENT_PREFIX,
  SortingLayerTable,
  SpriteAnimationAsset,
  SpriteAnimator,
  SpriteAtlasAsset,
  SpriteLayerEffect,
  SpriteLayerRegistry,
  SpriteRenderer,
  TILEMAP_ASSET_TYPE,
  TILEMAP_FILE_EXTENSIONS,
  TILEMAP_FORMAT,
  TILEMAP_FORMAT_VERSION,
  TINT_EFFECT_WGSL,
  TWO_D_ANIMATION_ORDER,
  TWO_D_ERROR_MESSAGES,
  TWO_D_MODES,
  TWO_D_SETTINGS_SECTION,
  TWO_D_SYNC_ORDER,
  Tilemap,
  TilemapAsset,
  TilemapRenderer,
  TwoDAnimationSystem,
  TwoDErrorCode,
  TwoDService,
  TwoDSyncSystem,
  asepriteFrameName,
  createSpriteAnimationLoader,
  createSpriteAtlasLoader,
  createTilemapLoader,
  decodeTileRle,
  defaultTwoDSettings,
  defineSpriteAnimation,
  defineSpriteAtlas,
  defineTilemap,
  describeSpriteAnimationFormat,
  describeSpriteAtlasFormat,
  describeTilemapFormat,
  describeTwoDSchemas,
  encodeTileRle,
  fieldInstancesToRecord,
  findTileset,
  gridAtlas,
  importAsepriteAnimations,
  importAsepriteAtlas,
  importLdtkLevel,
  importTexturePackerAtlas,
  importTiledMap,
  isFullCellSolid,
  mergeTileCollisions,
  normalisePath,
  parseSpriteFragment,
  pivotedPositionToRef,
  pixelsToWorldToRef,
  readVec2,
  resolveClipFrames,
  resolveRelative,
  selectCamera,
  sizeForZoom,
  snapPixel,
  snapZoomToInteger,
  spawnTilemapObjects,
  spriteAnimationFileSchema,
  spriteAnimationJsonSchema,
  spriteAtlasFileSchema,
  spriteAtlasJsonSchema,
  spriteLayerKey,
  spriteRotationFromLite,
  spriteRotationToLite,
  tileCollisionInfo,
  tileFrameName,
  tiledPropertiesToRecord,
  tilemapFileSchema,
  tilemapJsonSchema,
  twoD,
  twoDError,
  twoDSettingsSchema,
  viewRotationToLite,
  worldToPixelsToRef,
  zoomForSize,
  type AnimatedTilemapSink,
  type AsepriteAnimationImportOptions,
  type AsepriteImportOptions,
  type CollisionMergeOptions,
  type GridAtlasImportOptions,
  type LdtkImportOptions,
  type LiteAtlasTexture,
  type LiteBounds2D,
  type LiteSprite2DHandle,
  type LiteSprite2DLayer,
  type LiteSprite2DView,
  type LiteSpriteAtlas,
  type LiteSpriteBlendMode,
  type LiteSpriteFrame,
  type LiteSpritePickInfo,
  type LiteSpriteRenderer,
  type LiteSpriteSampling,
  type PlayClipOptions,
  type SpriteAnimationDefinition,
  type SpriteAnimationEvent,
  type SpriteAnimationInput,
  type SpriteAsset,
  type SpriteAtlasAssetLiteHandles,
  type SpriteAtlasDefinition,
  type SpriteAtlasInput,
  type SpriteBlendName,
  type SpriteClip,
  type SpriteClipDefinition,
  type SpriteEffectKind,
  type SpriteFrameDefinition,
  type SpriteFrameInfo,
  type SpriteLayerEntry,
  type SpriteLayerKey,
  type TexturePackerImportOptions,
  type TileAnimationFrame,
  type TileChange,
  type TileColliderDefinition,
  type TileCollisionInfo,
  type TileCollisionShape,
  type TileDefinition,
  type TileObjectContext,
  type TileObjectFactory,
  type TileRleData,
  type TiledImportOptions,
  type TilemapCollisionChunk,
  type TilemapCollisionData,
  type TilemapDefinition,
  type TilemapInput,
  type TilemapLayerDefinition,
  type TilemapLayerInput,
  type TilemapObjectDefinition,
  type TilesetDefinition,
  type TwoDErrorOptions,
  type TwoDLiteHandles,
  type TwoDMode,
  type TwoDOptions,
  type TwoDPick,
  type TwoDSettings,
  type Vec2Json,
  type WorldBox,
} from "@ignifx/2d";

// @ignifx/ui — DOM overlay host, layers, scaling, focus routing, WorldAnchor, Lite text, widgets, i18n.
// `VERSION`, `describeSchemas`, and `LiteFont` are deliberately absent: those names belong to @ignifx/core here.
export {
  Dialog,
  HUD_ANCHORS,
  HudText,
  I18N_ASSET_TYPE,
  I18N_FILE_EXTENSIONS,
  I18N_FORMAT,
  I18N_FORMAT_VERSION,
  I18nService,
  LoadingScreen,
  LocaleAsset,
  TEXT_ALIGNMENTS,
  TextComponent,
  TextRuntime,
  Toast,
  UI_CLASS_NAMES,
  UI_CSS_VARIABLES,
  UI_ERROR_MESSAGES,
  UI_FOCUS_ATTRIBUTE,
  UI_LAYER_Z_STEP,
  UI_SCALING_MODES,
  UI_SETTINGS_SECTION,
  UI_STYLE_ELEMENT_ID,
  UI_SYNC_ORDER,
  UiErrorCode,
  UiHost,
  UiLayer,
  UiSystem,
  VirtualButton,
  VirtualJoystick,
  WorldAnchor,
  WorldText,
  WorldText2D,
  asDomCanvas,
  computeAnchorPlacement,
  computeHudPlacement,
  computePivotPlacement,
  computeUiLayout,
  createLocaleLoader,
  createPluralSelector,
  defaultUiSettings,
  describeLocaleFileFormat,
  findVirtualDevice,
  isEditableElement,
  localeFileSchema,
  localeJsonSchema,
  parseLocaleFile,
  parseMessage,
  pixelMapping,
  progressFraction,
  renderMessage,
  resolveDomTarget,
  stickAxis,
  ui,
  uiError,
  uiSettingsSchema,
  type AnchorInput,
  type AnchorPlacement,
  type ArgumentNode,
  type DialogButton,
  type DialogOptions,
  type HudAnchor,
  type HudPlacement,
  type HudPlacementInput,
  type I18nServiceOptions,
  type LiteTextData,
  type LiteTextLayer,
  type LiteTextRenderable,
  type LiteTextRenderer,
  type LoadingScreenOptions,
  type LocaleDocument,
  type MessageNode,
  type MessageParams,
  type MessagePattern,
  type PluralNode,
  type PluralSelector,
  type TextAlignment,
  type TextMetrics,
  type TextNode,
  type TextRuntimeOptions,
  type ToastOptions,
  type UiDomTarget,
  type UiErrorOptions,
  type UiHostOptions,
  type UiLayerOptions,
  type UiLayout,
  type UiOptions,
  type UiPixelMapping,
  type UiScalingMode,
  type UiSettings,
  type UiSurfaceMetrics,
  type UiSystemOptions,
  type VirtualButtonOptions,
  type VirtualDeviceLike,
  type VirtualJoystickOptions,
} from "@ignifx/ui";

// @ignifx/3d — controllers, ThirdPersonCamera, Animator, navigation on Recast, LodGroup, Billboard.
// `VERSION`, `describeSchemas`, and `LiteAnimationGroup` are deliberately absent: those names belong to @ignifx/core here.
export {
  ANIMATOR_ASSET_TYPE,
  ANIMATOR_CONDITION_OPS,
  ANIMATOR_FILE_EXTENSIONS,
  ANIMATOR_FORMAT,
  ANIMATOR_FORMAT_VERSION,
  ANIMATOR_MASK_MODES,
  ANIMATOR_PARAMETER_KINDS,
  ANY_STATE,
  Animator,
  AnimatorAsset,
  AnimatorStateMachine,
  BILLBOARD_MODES,
  BILLBOARD_ORDER,
  Billboard,
  BillboardSystem,
  DEFAULT_CLIP_LENGTH,
  FirstPersonController,
  JumpTimers,
  LOD_CULLED,
  LOD_ORDER,
  LodGroup,
  LodSystem,
  NAVIGATION_ORDER,
  NAV_OBSTACLE_SHAPES,
  NavMeshAgent,
  NavMeshObstacle,
  NavMeshSurface,
  NavigationService,
  NavigationSystem,
  PlatformMover,
  Projectile,
  RigidbodyMover,
  THREE_D_ANIMATION_ORDER,
  THREE_D_ERROR_MESSAGES,
  THREE_D_SETTINGS_SECTION,
  ThirdPersonCamera,
  ThirdPersonController,
  ThreeDAnimationSystem,
  ThreeDErrorCode,
  WORLD_FORWARD,
  animatorFileSchema,
  cameraRelativeToRef,
  createAnimatorLoader,
  defaultStateOf,
  defaultThreeDSettings,
  defineAnimator,
  describeAnimatorFormat,
  jumpVelocity,
  mainCamera,
  mainCameraForward,
  projectOnSlopeToRef,
  slopeAngleDegrees,
  threeD,
  threeDError,
  threeDSettingsSchema,
  turnTowardsDegrees,
  yawFromDirection,
  type AnimatorBlendChildDefinition,
  type AnimatorBlendTreeDefinition,
  type AnimatorConditionDefinition,
  type AnimatorConditionOp,
  type AnimatorDefinition,
  type AnimatorEventDefinition,
  type AnimatorInput,
  type AnimatorLayerDefinition,
  type AnimatorMaskMode,
  type AnimatorParameterDefinition,
  type AnimatorParameterKind,
  type AnimatorPlayOptions,
  type AnimatorStateDefinition,
  type AnimatorTransitionDefinition,
  type BillboardMode,
  type ClipWeight,
  type LiteAnimationManager,
  type LiteNavCrowd,
  type LiteNavigationPlugin,
  type LiteObstacleHandle,
  type LodLevel,
  type NavObstacleShape,
  type PlayStateOptions,
  type StateChange,
  type ThreeDErrorOptions,
  type ThreeDOptions,
  type ThreeDSettings,
} from "@ignifx/3d";

// @ignifx/electron — the renderer-side extension: host detection, file-system storage, app.desktop.
// `VERSION` is deliberately absent: that name belongs to @ignifx/core here. The main-process and preload
// halves live at `@ignifx/electron/main` and `@ignifx/electron/preload`, which a game imports directly.
export {
  ELECTRON_ERROR_MESSAGES,
  ELECTRON_STORAGE_BACKEND_NAME,
  ElectronErrorCode,
  ElectronStorageBackend,
  HOST_CHANNELS,
  HOST_CONTRACT_MAJOR,
  HOST_CONTRACT_VERSION,
  HOST_GLOBAL_NAME,
  HOST_WINDOW_EVENT_CHANNEL,
  HostDesktop,
  IGNIFX_HOST_AUTHORITY,
  IGNIFX_ORIGIN,
  IGNIFX_SCHEME,
  QUOTA_MESSAGE_PREFIX,
  REQUIRED_HOST_MEMBERS,
  STORAGE_BACKEND_FAILED_CODE,
  STORAGE_QUOTA_CODE,
  STORAGE_VALUE_CORRUPT_CODE,
  UnavailableDesktop,
  assertHostContract,
  electron,
  electronError,
  findIgnifxHost,
  hostCallError,
  isCompatibleHostVersion,
  type Desktop,
  type ElectronErrorOptions,
  type ElectronOptions,
  type HostChannel,
  type HostDialogs,
  type HostFileFilter,
  type HostOpenDialogOptions,
  type HostOpenDialogResult,
  type HostPaths,
  type HostShell,
  type HostStorage,
  type HostStoredValue,
  type HostVersions,
  type HostWindow,
  type HostWindowEvent,
  type IgnifxHost,
} from "@ignifx/electron";

// @ignifx/devtools — the debug overlay, its panels, the inspector, the Console sink, the `devtools` settings.
// `VERSION` and `asDomCanvas` are deliberately absent: those names belong to @ignifx/core and @ignifx/ui here.
export {
  DEFAULT_DEVTOOLS_LOG_LIMIT,
  DEVTOOLS_CLASS_NAMES,
  DEVTOOLS_ERROR_LIMIT,
  DEVTOOLS_ERROR_MESSAGES,
  DEVTOOLS_HOT_RELOAD_LIMIT,
  DEVTOOLS_LAYER_Z_INDEX,
  DEVTOOLS_LOG_LEVELS,
  DEVTOOLS_PANEL_NAMES,
  DEVTOOLS_POSITIONS,
  DEVTOOLS_SAMPLE_ORDER,
  DEVTOOLS_SETTINGS_SECTION,
  DEVTOOLS_STYLE_ELEMENT_ID,
  DEVTOOLS_UI_LAYER,
  DevtoolsErrorCode,
  DevtoolsService,
  TEXT_REFRESH_HZ,
  createDevtoolsLogSink,
  defaultDevtoolsSettings,
  devtools,
  devtoolsError,
  devtoolsSettingsSchema,
  resolveDevtoolsTarget,
  type DevtoolsDomTarget,
  type DevtoolsErrorOptions,
  type DevtoolsLogSink,
  type DevtoolsLogSinkOptions,
  type DevtoolsOptions,
  type DevtoolsPanelHandle,
  type DevtoolsPanelName,
  type DevtoolsPosition,
  type DevtoolsServiceOptions,
  type DevtoolsSettings,
} from "@ignifx/devtools";
