import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { renderLlmsIndex } from "../lib/llms-index.ts";

let root = "";

/** The `blob/main` prefix `lib/llms-index.ts` builds every URL from. */
const BLOB = "https://github.com/astrum-forge/ignifx/blob/main";

/**
 * Writes one file inside the fixture tree, creating its directories.
 *
 * @param relativePath - Path relative to the fixture root.
 * @param contents - File contents.
 */
function write(relativePath: string, contents: string): void {
  const file = path.join(root, relativePath);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, contents, "utf8");
}

beforeAll(() => {
  root = mkdtempSync(path.join(tmpdir(), "ignifx-llms-fixture-"));
  write(
    "skills/ignifx/SKILL.md",
    "---\nname: ignifx\ndescription: Builds games with ignifx. Use when the user mentions ignifx.\n" +
      'license: Apache-2.0\nmetadata:\n  ignifx-version: "0.0.0"\n---\n\n' +
      "# ignifx\n\n## What this is / when to use\n\nignifx is a code-first engine. More prose.\n",
  );
  write("skills/ignifx/references/gotchas.md", "# Gotchas\n\nTraps and their replacements. Second sentence.\n");
  write("skills/ignifx/references/concepts/lifecycle.md", "# Lifecycle\n\nWhen things happen in a frame.\n");
  write("skills/ignifx/references/recipes/README.md", "# Recipes\n\nAn index page that is not listed.\n");
  write("skills/ignifx/references/recipes/spawn.md", "# Spawn a prefab\n\nStamp copies of a prefab out.\n");
  write(
    "skills/ignifx/references/formats/components.md",
    "# components\n\n<!-- Generated by `pnpm docs:schemas`. Do not edit by hand. -->\n\n" +
      "## Animator (`ignifx/Animator`)\n\n| Field | Kind |\n|---|---|\n| `a` | `str` |\n",
  );
  write("skills/ignifx/references/api/core.md", "# @ignifx/core\n\nThe public barrel. And more text.\n");
  write(
    "packages/audio/package.json",
    JSON.stringify({ name: "@ignifx/audio", ignifx: { skill: "./skills/audio/SKILL.md" } }),
  );
  write(
    "packages/audio/skills/audio/SKILL.md",
    "---\nname: audio\ndescription: Plays sound.\nlicense: Apache-2.0\n---\n\n" +
      "# @ignifx/audio\n\n## What this is / when to use\n\nPlays sound in an ignifx game. More prose.\n",
  );
});

afterAll(() => {
  rmSync(root, { recursive: true, force: true });
});

describe("docs:llms", () => {
  it("is deterministic", () => {
    expect(renderLlmsIndex(root)).toBe(renderLlmsIndex(root));
  });

  it("opens with the llms.txt preamble taken from the entry skill", () => {
    const lines = renderLlmsIndex(root).split("\n");
    expect(lines[0]).toContain("Generated by `pnpm docs:llms`");
    expect(lines[2]).toBe("# ignifx");
    expect(lines[4]).toBe("> Builds games with ignifx.");
  });

  it("links every page of the fixture tree at its file in the repository", () => {
    const output = renderLlmsIndex(root);
    expect(output).toContain(`- [ignifx](${BLOB}/skills/ignifx/SKILL.md): ignifx is a code-first engine.`);
    expect(output).toContain(`- [Gotchas](${BLOB}/skills/ignifx/references/gotchas.md): Traps and their replacements.`);
    expect(output).toContain(
      `- [Lifecycle](${BLOB}/skills/ignifx/references/concepts/lifecycle.md): When things happen in a frame.`,
    );
    expect(output).toContain(
      `- [Spawn a prefab](${BLOB}/skills/ignifx/references/recipes/spawn.md): Stamp copies of a prefab out.`,
    );
    expect(output).toContain(`- [@ignifx/core](${BLOB}/skills/ignifx/references/api/core.md): The public barrel.`);
    expect(output).toContain(
      `- [@ignifx/audio](${BLOB}/packages/audio/skills/audio/SKILL.md): Plays sound in an ignifx game.`,
    );
  });

  it("serves no site route, so an agent is never sent to a page the site does not render", () => {
    // ADR-0020: the `/skill/**` tree left the site and `_redirects` points those URLs here.
    for (const line of renderLlmsIndex(root).split("\n")) {
      if (line.startsWith("- [")) {
        expect(line, line).toContain(`](${BLOB}/`);
      }
    }
  });

  it("falls back to the generator for a page that is a table, and skips README.md", () => {
    const output = renderLlmsIndex(root);
    expect(output).toContain(
      `- [components](${BLOB}/skills/ignifx/references/formats/components.md): Generated by \`pnpm docs:schemas\`.`,
    );
    expect(output).not.toContain("/references/recipes/README");
  });

  it("refuses a tree with no entry skill", () => {
    const empty = mkdtempSync(path.join(tmpdir(), "ignifx-llms-empty-"));
    expect(() => renderLlmsIndex(empty)).toThrow(/no entry skill/u);
    rmSync(empty, { recursive: true, force: true });
  });
});
